# Generated by Skyramp v1.3.44 on 2026-09-12 18:56:33.328586851 +0000 UTC m=+1610.550023844
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output admin_notification_create_rejections_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_admin_notification_create_rejections.json

# Import of required libraries
import skyramp
import os
import time
import re
import json
import uuid


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

UUID_RE = r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
ISO_RE = r"^\d{4}-\d{2}-\d{2}T"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")
    headers["Content-Type"] = "application/json"

    run = uuid.uuid4().hex[:8]

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    user_id = skyramp.get_response_value(me_GET_response, "id")
    assert re.match(UUID_RE, str(user_id), re.IGNORECASE)

    valid_title = "testbot-create-valid-" + run
    valid_description = "testbot create description " + run
    max_title = "a" * 255
    over_max_title = "a" * 256

    # A valid notice is created and echoes back what was sent
    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"userId": user_id, "title": valid_title, "description": valid_description, "level": "warning"}),
        headers=headers
    )
    assert notifications_POST_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_response, "title") == valid_title
    assert skyramp.get_response_value(notifications_POST_response, "description") == valid_description
    assert skyramp.get_response_value(notifications_POST_response, "level") == "warning"
    assert skyramp.get_response_value(notifications_POST_response, "type") == "Custom"
    assert skyramp.get_response_value(notifications_POST_response, "readAt") is None
    assert re.match(ISO_RE, str(skyramp.get_response_value(notifications_POST_response, "createdAt")))
    valid_id = skyramp.get_response_value(notifications_POST_response, "id")
    assert re.match(UUID_RE, str(valid_id), re.IGNORECASE)

    # An empty title is refused
    notifications_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"userId": user_id, "title": ""}),
        headers=headers
    )
    assert notifications_POST_1_response.status_code == 400
    assert skyramp.get_response_value(notifications_POST_1_response, "message") == "Validation failed"
    assert skyramp.get_response_value(notifications_POST_1_response, "errors.0.path.0") == "title"
    assert skyramp.get_response_value(notifications_POST_1_response, "errors.1") is None
    assert skyramp.get_response_value(notifications_POST_1_response, "id") is None

    # A whitespace-only title is refused once trimmed
    notifications_POST_2_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"userId": user_id, "title": "   "}),
        headers=headers
    )
    assert notifications_POST_2_response.status_code == 400
    assert skyramp.get_response_value(notifications_POST_2_response, "message") == "Validation failed"
    assert skyramp.get_response_value(notifications_POST_2_response, "errors.0.path.0") == "title"
    assert skyramp.get_response_value(notifications_POST_2_response, "errors.1") is None
    assert skyramp.get_response_value(notifications_POST_2_response, "id") is None

    # A 256 character title is over the bound
    notifications_POST_3_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"userId": user_id, "title": over_max_title}),
        headers=headers
    )
    assert notifications_POST_3_response.status_code == 400
    assert skyramp.get_response_value(notifications_POST_3_response, "message") == "Validation failed"
    assert skyramp.get_response_value(notifications_POST_3_response, "errors.0.path.0") == "title"
    assert skyramp.get_response_value(notifications_POST_3_response, "errors.1") is None
    assert skyramp.get_response_value(notifications_POST_3_response, "id") is None

    # A missing title is refused
    notifications_POST_4_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"userId": user_id}),
        headers=headers
    )
    assert notifications_POST_4_response.status_code == 400
    assert skyramp.get_response_value(notifications_POST_4_response, "message") == "Validation failed"
    assert skyramp.get_response_value(notifications_POST_4_response, "errors.0.path.0") == "title"
    assert skyramp.get_response_value(notifications_POST_4_response, "errors.1") is None
    assert skyramp.get_response_value(notifications_POST_4_response, "id") is None

    # A recipient no user has is refused
    notifications_POST_5_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"userId": "11111111-2222-4333-8444-555555555555", "title": "testbot-create-orphan-" + run}),
        headers=headers
    )
    assert notifications_POST_5_response.status_code == 400
    assert skyramp.get_response_value(notifications_POST_5_response, "message") == "User not found"
    assert skyramp.get_response_value(notifications_POST_5_response, "id") is None

    # A missing recipient is refused
    notifications_POST_6_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"title": "testbot-create-nouser-" + run}),
        headers=headers
    )
    assert notifications_POST_6_response.status_code == 400
    assert skyramp.get_response_value(notifications_POST_6_response, "message") == "Validation failed"
    assert skyramp.get_response_value(notifications_POST_6_response, "errors.0.path.0") == "userId"
    assert skyramp.get_response_value(notifications_POST_6_response, "errors.1") is None
    assert skyramp.get_response_value(notifications_POST_6_response, "id") is None

    # A 255 character title is still accepted
    notifications_POST_7_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"userId": user_id, "title": max_title}),
        headers=headers
    )
    assert notifications_POST_7_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_7_response, "title") == max_title
    assert skyramp.get_response_value(notifications_POST_7_response, "level") == "info"
    max_title_id = skyramp.get_response_value(notifications_POST_7_response, "id")
    assert re.match(UUID_RE, str(max_title_id), re.IGNORECASE)

    # Delete both records this test created
    api_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=json.dumps({"ids": [valid_id, max_title_id]}),
        headers=headers
    )
    assert api_notifications_DELETE_response.status_code == 204

    gone_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/" + str(valid_id),
        method="GET",
        headers=headers
    )
    assert gone_GET_response.status_code == 404
    assert skyramp.get_response_value(gone_GET_response, "message") == "Notification not found"
