// Generated by Skyramp v1.3.44 on 2026-09-08 21:29:23.057618407 +0000 UTC m=+2574.380657298
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output admin_send_notification.spec.ts \
// 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/immich-testb/immich-testb/.skyramp/admin_send_notification_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:2285");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(244000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => pageErrors.push(error.message));

    await page.goto(`${baseUrl}/auth/logout`);
    await page.evaluate(() => { localStorage.removeItem('appVersion'); return { appVersion: localStorage.getItem('appVersion') }; });
    await page.goto(`${baseUrl}/auth/login`);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@immich.test",
        "password": "password"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/auth/login**");
    await page.getByRole("button", { name: "Login" }).click();
    const response0 = await responsePromise0;

    expect(response0.status()).toBe(201);
    const loginBody = await response0.json();
    expect(getValue(loginBody, "userEmail")).toBe("admin@immich.test");
    expect(getValue(loginBody, "isAdmin")).toBe(true);
    expect(getValue(loginBody, "userId")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(loginBody, "accessToken")).not.toBeNull();

    await page.getByRole("button", { name: "Acknowledge" }).click();
    await page.goto(`${baseUrl}/admin/users`);
    await page.getByRole("link", { name: "Admin" }).click();
    await expect(page.getByTestId("send-notification-submit")).toBeDisabled();

    const playwrightRequest1: Record<string, any> = {
        "description": "Quarterly archive summary is ready",
        "level": "warning",
        "title": "Skyramp Release Digest"
    };

    await page.getByTestId("send-notification-title").fill(getValue(playwrightRequest1, "title"));
    await page.getByTestId("send-notification-description").fill(getValue(playwrightRequest1, "description"));
    await page.getByTestId("send-notification-level").selectOption(getValue(playwrightRequest1, "level"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/**/notifications**");
    await page.getByTestId("send-notification-submit").click();
    const response1 = await responsePromise1;

    expect(response1.status()).toBe(201);
    const notificationCreated = await response1.json();
    expect(getValue(notificationCreated, "id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(notificationCreated, "createdAt")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getValue(notificationCreated, "title")).toBe("Skyramp Release Digest");
    expect(getValue(notificationCreated, "description")).toBe("Quarterly archive summary is ready");
    expect(getValue(notificationCreated, "level")).toBe("warning");
    expect(getValue(notificationCreated, "type")).toBe("Custom");

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByTestId("send-notification-submit")).toBeDisabled();
    await page.getByRole("link", { name: "Immich logo" }).click();
    await page.getByRole("button", { name: "Notifications" }).click();
    await expect(page.getByTestId("notification-item")).toContainText("Skyramp Release Digest");
    await expect(page.getByTestId("notification-item")).toContainText("Quarterly archive summary is ready");
    await expect(page.getByTestId("notification-clear-read")).toBeDisabled();
    await page.getByRole("button", { name: "Mark all as read" }).click();
    await expect(page.getByTestId("notification-clear-read")).toBeEnabled();
    await page.getByTestId("notification-show-read").click();
    await expect(page.getByTestId("notification-item")).toContainText("Skyramp Release Digest");
    await page.getByTestId("notification-clear-read").click();
    await expect(page.getByText("Skyramp Release Digest", { exact: true })).toBeHidden();
    await expect(page.getByTestId("notification-unread-badge")).toBeHidden();
    expect(pageErrors).toEqual([]);
});
