// Generated by Skyramp v1.3.44 on 2026-09-08 21:35:39.034753083 +0000 UTC m=+1980.407861406
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output admin_send_notification_and_remove.spec.ts \
// 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/immich-testb/immich-testb/.skyramp/admin_send_notification_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, uniqueSuffix, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:2285");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(171000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => pageErrors.push(error.message));

    // Run-unique value(s) for unique-constrained create field(s): keeps this test idempotent across re-runs
    const uniqueSendNotificationTitle = uniqueSuffix("");

    await page.goto(`${baseUrl}/auth/login`);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@immich.test",
        "password": "password"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/auth/login**");
    await page.getByRole("button", { name: "Login" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(201);
    const loginBody = await response0.json();
    expect(loginBody.userEmail).toBe(getValue(playwrightRequest0, "email"));
    expect(loginBody.isAdmin).toBe(true);

    await page.getByRole("button", { name: "Acknowledge" }).click();
    await page.goto(`${baseUrl}/admin/users`);
    await page.getByRole("link", { name: "Admin" }).click();
    await expect(page.getByTestId("send-notification-submit")).toBeDisabled();

    const playwrightRequest1: Record<string, any> = {
        "description": "Sent by the Skyramp UI test",
        "title": "Skyramp Notice Alpha"
    };

    await page.getByTestId("send-notification-title").fill(uniqueSendNotificationTitle);
    await page.getByTestId("send-notification-description").fill(getValue(playwrightRequest1, "description"));
    await expect(page.getByTestId("send-notification-submit")).toBeEnabled();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/**/notifications**");
    await page.getByTestId("send-notification-submit").click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(201);
    const createdNotification = await response1.json();
    expect(createdNotification.title).toBe(uniqueSendNotificationTitle);
    expect(createdNotification.description).toBe(getValue(playwrightRequest1, "description"));
    expect(createdNotification.level).toBe("info");
    expect(createdNotification.type).toBe("Custom");
    expect(createdNotification.id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto(`${baseUrl}/photos`);
    await page.getByRole("button", { name: "Notifications" }).click();
    await expect(page.getByTestId("notification-unread-badge")).toHaveText("1");
    await expect(page.getByTestId("notification-item")).toContainText(uniqueSendNotificationTitle);
    await expect(page.getByTestId("notification-item")).toContainText("Sent by the Skyramp UI test");
    await page.getByTestId("notification-remove").click();
    await expect(page.getByTestId("notification-unread-badge")).toBeHidden();
    await expect(page.getByTestId("notification-item")).toBeHidden();
    await expect(page.getByText("No notifications", { exact: true })).toBeVisible();
    expect(pageErrors).toEqual([]);
});
