// Generated by Skyramp v1.3.44 on 2026-09-12 18:56:46.820107127 +0000 UTC m=+1624.041544140
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output admin_send_notification.spec.ts \
// 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/immich-testb/immich-testb/.skyramp/admin_send_notification_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, uniqueSuffix, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:2285");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(898000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Run-unique value(s) for unique-constrained create field(s): keeps this test idempotent across re-runs
    const uniqueSendNotificationTitle = uniqueSuffix("");

    await page.goto(`${baseUrl}/auth/login`);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@immich.test",
        "password": "EvalPass123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/auth/login**");
    await page.getByRole("button", { name: "Login" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(201);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Notifications" }).click();
    await page.goto(`${baseUrl}/admin/users`);
    await page.getByRole("link", { name: "Immich Admin" }).click();
    await page.goto(`${baseUrl}/auth/login`);
    await page.goto(`${baseUrl}/auth/logout`);
    await page.goto(`${baseUrl}/auth/login`);

    const playwrightRequest1: Record<string, any> = {
        "email": "admin@immich.test",
        "password": "EvalPass123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest1, "email"));
    await page.locator("#password").fill(getValue(playwrightRequest1, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/auth/login**");
    await page.getByRole("button", { name: "Login" }).click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(201);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto(`${baseUrl}/admin/users`);
    await page.getByRole("link", { name: "Immich Admin" }).click();

    const playwrightRequest2: Record<string, any> = {
        "description": "Sent from the admin user page by Testbot",
        "title": "Testbot notice alpha"
    };

    await page.getByTestId("send-notification-title").fill(uniqueSendNotificationTitle);
    await page.getByTestId("send-notification-description").fill(getValue(playwrightRequest2, "description"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/api/**/notifications**");
    await page.getByTestId("send-notification-submit").click();
    const response2 = await responsePromise2;
    expect(response2.status()).toBe(201);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByTestId("send-notification-submit")).toBeDisabled();
    await page.goto(`${baseUrl}/photos`);
    await page.getByRole("button", { name: "Notifications" }).click();
    await page.getByTestId("notification-search").fill("zzz-no-such-notice");
    await expect(page.getByTestId("notification-item")).toHaveCount(0);
    await page.getByTestId("notification-search").fill(uniqueSendNotificationTitle);
    await expect(page.getByTestId("notification-item")).toHaveCount(1);
    await expect(page.getByTestId("notification-item")).toContainText(uniqueSendNotificationTitle);
    await expect(page.getByTestId("notification-item")).toContainText("Sent from the admin user page by Testbot");
    await page.getByTestId("notification-remove").click();
    await expect(page.getByTestId("notification-item")).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Mark all as read" })).toBeDisabled();
});
