# Generated by Skyramp v1.3.44 on 2026-09-12 18:56:22.445470421 +0000 UTC m=+1599.666907425
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notification_get_one_by_id_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notification_get_one_by_id.json

# Import of required libraries
import skyramp
import os
import time
import re
import json
import uuid


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

UUID_RE = r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
ISO_RE = r"^\d{4}-\d{2}-\d{2}T"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")
    headers["Content-Type"] = "application/json"

    run = uuid.uuid4().hex[:8]

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    user_id = skyramp.get_response_value(me_GET_response, "id")
    assert re.match(UUID_RE, str(user_id), re.IGNORECASE)

    title = "testbot-getone-" + run
    description = "testbot getone description " + run

    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"userId": user_id, "title": title, "description": description, "level": "warning"}),
        headers=headers
    )
    assert notifications_POST_response.status_code == 201
    notification_id = skyramp.get_response_value(notifications_POST_response, "id")
    assert re.match(UUID_RE, str(notification_id), re.IGNORECASE)

    # The single fetch returns the notice with the fields it was created with
    notifications_notifications_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/" + str(notification_id),
        method="GET",
        headers=headers
    )
    assert notifications_notifications_GET_response.status_code == 200
    assert skyramp.get_response_value(notifications_notifications_GET_response, "id") == notification_id
    assert skyramp.get_response_value(notifications_notifications_GET_response, "title") == title
    assert skyramp.get_response_value(notifications_notifications_GET_response, "description") == description
    assert skyramp.get_response_value(notifications_notifications_GET_response, "level") == "warning"
    assert skyramp.get_response_value(notifications_notifications_GET_response, "type") == "Custom"
    assert skyramp.get_response_value(notifications_notifications_GET_response, "readAt") is None
    assert re.match(ISO_RE, str(skyramp.get_response_value(notifications_notifications_GET_response, "createdAt")))

    # An id no notification has
    notifications_11111111_2222_4333_8444_555555555555_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/11111111-2222-4333-8444-555555555555",
        method="GET",
        headers=headers
    )
    assert notifications_11111111_2222_4333_8444_555555555555_GET_response.status_code == 404
    assert skyramp.get_response_value(notifications_11111111_2222_4333_8444_555555555555_GET_response, "message") == "Notification not found"
    assert skyramp.get_response_value(notifications_11111111_2222_4333_8444_555555555555_GET_response, "title") is None

    # A malformed id
    not_a_uuid_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/not-a-uuid",
        method="GET",
        headers=headers
    )
    assert not_a_uuid_GET_response.status_code == 400
    assert skyramp.get_response_value(not_a_uuid_GET_response, "message") == "Validation failed"
    assert skyramp.get_response_value(not_a_uuid_GET_response, "errors.0.path.0") == "id"
    assert skyramp.get_response_value(not_a_uuid_GET_response, "errors.1") is None
    assert skyramp.get_response_value(not_a_uuid_GET_response, "title") is None

    # Delete the record this test created
    notifications_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/" + str(notification_id),
        method="DELETE",
        headers=headers
    )
    assert notifications_notifications_DELETE_response.status_code == 204

    # A deleted notice is refused the same way a missing one is
    notifications_notifications_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/" + str(notification_id),
        method="GET",
        headers=headers
    )
    assert notifications_notifications_GET_1_response.status_code == 404
    assert skyramp.get_response_value(notifications_notifications_GET_1_response, "message") == "Notification not found"
    assert skyramp.get_response_value(notifications_notifications_GET_1_response, "title") is None
