# Generated by Skyramp v1.3.44 on 2026-09-12 18:56:38.997170643 +0000 UTC m=+1616.218607646
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notification_search_literal_wildcard_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notification_search_literal_wildcard.json

# Import of required libraries
import skyramp
import os
import time
import re
import json
import uuid


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

UUID_RE = r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
ISO_RE = r"^\d{4}-\d{2}-\d{2}T"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")
    headers["Content-Type"] = "application/json"

    run = uuid.uuid4().hex[:8]

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    user_id = skyramp.get_response_value(me_GET_response, "id")
    assert re.match(UUID_RE, str(user_id), re.IGNORECASE)

    anchor_title = "testbotpctanchor" + run
    percent_title = "testbotpct50%off" + run
    # Same text as anchor_title with its first character replaced by an underscore.
    # No notification title contains this literal text.
    underscore_term = "_" + anchor_title[1:]

    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"userId": user_id, "title": anchor_title}),
        headers=headers
    )
    assert notifications_POST_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_response, "title") == anchor_title
    anchor_id = skyramp.get_response_value(notifications_POST_response, "id")
    assert re.match(UUID_RE, str(anchor_id), re.IGNORECASE)

    notifications_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"userId": user_id, "title": percent_title}),
        headers=headers
    )
    assert notifications_POST_1_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_1_response, "title") == percent_title
    percent_id = skyramp.get_response_value(notifications_POST_1_response, "id")
    assert re.match(UUID_RE, str(percent_id), re.IGNORECASE)

    try:
        # A search for a percent sign is a search for that character as text,
        # so only the notice whose title literally contains one may come back.
        api_notifications_GET_response = client.send_request(
            url=URL_localhost,
            path="/api/notifications",
            method="GET",
            headers=headers,
            query_params={"search": ["%"]}
        )
        assert api_notifications_GET_response.status_code == 200
        assert skyramp.get_response_value(api_notifications_GET_response, "0.id") == percent_id
        assert skyramp.get_response_value(api_notifications_GET_response, "0.title") == percent_title
        assert skyramp.get_response_value(api_notifications_GET_response, "1") is None

        # An underscore is text too, so a term no title contains matches nothing.
        api_notifications_GET_1_response = client.send_request(
            url=URL_localhost,
            path="/api/notifications",
            method="GET",
            headers=headers,
            query_params={"search": [underscore_term]}
        )
        assert api_notifications_GET_1_response.status_code == 200
        assert skyramp.get_response_value(api_notifications_GET_1_response, "0") is None
        assert skyramp.get_response_value(api_notifications_GET_1_response, "message") is None
    finally:
        # Delete both records this test created
        api_notifications_DELETE_response = client.send_request(
            url=URL_localhost,
            path="/api/notifications",
            method="DELETE",
            body=json.dumps({"ids": [anchor_id, percent_id]}),
            headers=headers
        )
        assert api_notifications_DELETE_response.status_code == 204
