# Generated by Skyramp v1.3.44 on 2026-09-08 21:14:39.269270421 +0000 UTC m=+1565.853560146
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notification_create_title_validation_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notification_create_title_validation.json

# Import of required libraries
import skyramp
import os
import re
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    assert skyramp.get_response_value(me_GET_response, "isAdmin") is True

    # Request Body
    notifications_POST_request_body = r'''{
        "level": "info",
        "title": "Skyramp title validation probe",
        "userId": "6ecb082e-4c2a-4668-ab6d-0bd4091f9c13"
    }'''

    # Execute Request
    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_request_body,
        headers=headers,
        data_override={"userId": skyramp.get_response_value(me_GET_response, "id")}
    )

    # Generated Assertions
    assert notifications_POST_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_response, "title") == "Skyramp title validation probe"
    assert skyramp.get_response_value(notifications_POST_response, "level") == "info"
    assert skyramp.get_response_value(notifications_POST_response, "type") == "Custom"
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(notifications_POST_response, "id"), re.I)

    # Request Body
    notifications_POST_1_request_body = r'''{
        "title": "   ",
        "userId": "6ecb082e-4c2a-4668-ab6d-0bd4091f9c13"
    }'''

    # Execute Request
    notifications_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_1_request_body,
        headers=headers
    )

    # Generated Assertions
    assert notifications_POST_1_response.status_code == 400
    assert skyramp.get_response_value(notifications_POST_1_response, "message") == "Validation failed"
    assert skyramp.get_response_value(notifications_POST_1_response, "errors.0.path.0") == "title"
    assert skyramp.get_response_value(notifications_POST_1_response, "errors.1") is None
    assert skyramp.get_response_value(notifications_POST_1_response, "errors.0.code") == "too_small"
    assert skyramp.get_response_value(notifications_POST_1_response, "errors.0.minimum") == 1
    assert skyramp.get_response_value(notifications_POST_1_response, "id") is None

    # Request Body
    notifications_POST_2_request_body = r'''{
        "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "userId": "6ecb082e-4c2a-4668-ab6d-0bd4091f9c13"
    }'''

    # Execute Request
    notifications_POST_2_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_2_request_body,
        headers=headers
    )

    # Generated Assertions
    assert notifications_POST_2_response.status_code == 400
    assert skyramp.get_response_value(notifications_POST_2_response, "message") == "Validation failed"
    assert skyramp.get_response_value(notifications_POST_2_response, "errors.0.path.0") == "title"
    assert skyramp.get_response_value(notifications_POST_2_response, "errors.1") is None
    assert skyramp.get_response_value(notifications_POST_2_response, "errors.0.code") == "too_big"
    assert skyramp.get_response_value(notifications_POST_2_response, "errors.0.maximum") == 255
    assert skyramp.get_response_value(notifications_POST_2_response, "id") is None

    # Request Body
    notifications_POST_3_request_body = r'''{
        "userId": "6ecb082e-4c2a-4668-ab6d-0bd4091f9c13"
    }'''

    # Execute Request
    notifications_POST_3_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_3_request_body,
        headers=headers
    )

    # Generated Assertions
    assert notifications_POST_3_response.status_code == 400
    assert skyramp.get_response_value(notifications_POST_3_response, "message") == "Validation failed"
    assert skyramp.get_response_value(notifications_POST_3_response, "errors.0.path.0") == "title"
    assert skyramp.get_response_value(notifications_POST_3_response, "errors.1") is None
    assert skyramp.get_response_value(notifications_POST_3_response, "errors.0.code") == "invalid_type"
    assert skyramp.get_response_value(notifications_POST_3_response, "id") is None

    # Execute Request
    notifications_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="DELETE",
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_response, "id")}
    )

    # Generated Assertions
    assert notifications_notifications_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
