# Generated by Skyramp v1.3.44 on 2026-09-12 18:56:25.07253845 +0000 UTC m=+1602.293975453
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notification_search_filter_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notification_search_filter.json

# Import of required libraries
import skyramp
import os
import time
import re
import json
import uuid


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

UUID_RE = r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
ISO_RE = r"^\d{4}-\d{2}-\d{2}T"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")
    headers["Content-Type"] = "application/json"

    run = uuid.uuid4().hex[:8]

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    user_id = skyramp.get_response_value(me_GET_response, "id")
    assert re.match(UUID_RE, str(user_id), re.IGNORECASE)

    alpha_title = "testbotsearchalpha" + run
    alpha_description = "testbotcharliedesc" + run
    bravo_title = "testbotsearchbravo" + run
    absent_term = "testbotzulunosuchterm" + run
    max_term = "a" * 255
    over_max_term = "a" * 256

    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"userId": user_id, "title": alpha_title, "description": alpha_description}),
        headers=headers
    )
    assert notifications_POST_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_response, "title") == alpha_title
    assert skyramp.get_response_value(notifications_POST_response, "description") == alpha_description
    alpha_id = skyramp.get_response_value(notifications_POST_response, "id")
    assert re.match(UUID_RE, str(alpha_id), re.IGNORECASE)

    notifications_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"userId": user_id, "title": bravo_title}),
        headers=headers
    )
    assert notifications_POST_1_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_1_response, "title") == bravo_title
    bravo_id = skyramp.get_response_value(notifications_POST_1_response, "id")
    assert re.match(UUID_RE, str(bravo_id), re.IGNORECASE)

    # A title fragment returns only the notice whose title carries it
    api_notifications_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": [alpha_title]}
    )
    assert api_notifications_GET_response.status_code == 200
    assert skyramp.get_response_value(api_notifications_GET_response, "0.id") == alpha_id
    assert skyramp.get_response_value(api_notifications_GET_response, "0.title") == alpha_title
    assert skyramp.get_response_value(api_notifications_GET_response, "0.description") == alpha_description
    assert skyramp.get_response_value(api_notifications_GET_response, "1") is None

    # A description fragment matches too, and still returns only that notice
    api_notifications_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": [alpha_description]}
    )
    assert api_notifications_GET_1_response.status_code == 200
    assert skyramp.get_response_value(api_notifications_GET_1_response, "0.id") == alpha_id
    assert skyramp.get_response_value(api_notifications_GET_1_response, "0.title") == alpha_title
    assert skyramp.get_response_value(api_notifications_GET_1_response, "1") is None

    # A term in neither notice returns an empty list
    api_notifications_GET_2_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": [absent_term]}
    )
    assert api_notifications_GET_2_response.status_code == 200
    assert skyramp.get_response_value(api_notifications_GET_2_response, "0") is None
    assert skyramp.get_response_value(api_notifications_GET_2_response, "message") is None

    # An empty term is refused
    api_notifications_GET_3_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": [""]}
    )
    assert api_notifications_GET_3_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_GET_3_response, "message") == "Validation failed"
    assert skyramp.get_response_value(api_notifications_GET_3_response, "errors.0.path.0") == "search"
    assert skyramp.get_response_value(api_notifications_GET_3_response, "errors.1") is None
    assert skyramp.get_response_value(api_notifications_GET_3_response, "0") is None

    # 256 characters is over the bound
    api_notifications_GET_4_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": [over_max_term]}
    )
    assert api_notifications_GET_4_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_GET_4_response, "message") == "Validation failed"
    assert skyramp.get_response_value(api_notifications_GET_4_response, "errors.0.path.0") == "search"
    assert skyramp.get_response_value(api_notifications_GET_4_response, "errors.1") is None
    assert skyramp.get_response_value(api_notifications_GET_4_response, "0") is None

    # 255 characters is still accepted
    api_notifications_GET_5_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": [max_term]}
    )
    assert api_notifications_GET_5_response.status_code == 200
    assert skyramp.get_response_value(api_notifications_GET_5_response, "message") is None

    # Delete both records this test created
    api_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=json.dumps({"ids": [alpha_id, bravo_id]}),
        headers=headers
    )
    assert api_notifications_DELETE_response.status_code == 204

    after_cleanup_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": [alpha_title]}
    )
    assert after_cleanup_GET_response.status_code == 200
    assert skyramp.get_response_value(after_cleanup_GET_response, "0") is None
