# Generated by Skyramp v1.3.44 on 2026-09-08 21:28:57.046769235 +0000 UTC m=+2548.369808116
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notification_search_filters_title_and_description_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notification_search_filters_title_and_description.json

# Import of required libraries
import skyramp
import json
import os
import re
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    search = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(me_GET_response, "id"), re.I)
    assert "@" in skyramp.get_response_value(me_GET_response, "email")
    assert skyramp.get_response_value(me_GET_response, "isAdmin") == True

    # Request Body
    notifications_POST_request_body = r'''{
        "description": "nightly archive job completed",
        "title": "Skyramp Search Alpha",
        "userId": "1293a3b5-2b75-4f56-9dac-244b2996cf86"
    }'''

    # Execute Request
    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_request_body,
        headers=headers,
        data_override={"userId": skyramp.get_response_value(me_GET_response, "id")}
    )

    # Generated Assertions
    assert notifications_POST_response.status_code == 201
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(notifications_POST_response, "id"), re.I)
    assert re.match(r"^\d{4}-\d{2}-\d{2}T", skyramp.get_response_value(notifications_POST_response, "createdAt"))
    assert skyramp.get_response_value(notifications_POST_response, "title") == "Skyramp Search Alpha"
    assert skyramp.get_response_value(notifications_POST_response, "description") == "nightly archive job completed"
    assert skyramp.get_response_value(notifications_POST_response, "level") == "info"
    assert skyramp.get_response_value(notifications_POST_response, "type") == "Custom"

    # Request Body
    notifications_POST_1_request_body = r'''{
        "description": "library scan aborted early",
        "title": "Skyramp Search Beta",
        "userId": "1293a3b5-2b75-4f56-9dac-244b2996cf86"
    }'''

    # Execute Request
    notifications_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_1_request_body,
        headers=headers,
        data_override={"userId": skyramp.get_response_value(me_GET_response, "id")}
    )

    # Generated Assertions
    assert notifications_POST_1_response.status_code == 201
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(notifications_POST_1_response, "id"), re.I)
    assert re.match(r"^\d{4}-\d{2}-\d{2}T", skyramp.get_response_value(notifications_POST_1_response, "createdAt"))
    assert skyramp.get_response_value(notifications_POST_1_response, "title") == "Skyramp Search Beta"
    assert skyramp.get_response_value(notifications_POST_1_response, "description") == "library scan aborted early"
    assert skyramp.get_response_value(notifications_POST_1_response, "level") == "info"
    assert skyramp.get_response_value(notifications_POST_1_response, "type") == "Custom"
    assert skyramp.get_response_value(notifications_POST_1_response, "id") != skyramp.get_response_value(notifications_POST_response, "id")

    # Execute Request
    api_notifications_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": ["Alpha"]}
    )

    # Generated Assertions
    assert api_notifications_GET_response.status_code == 200
    assert skyramp.get_response_value(api_notifications_GET_response, "0.id") == skyramp.get_response_value(notifications_POST_response, "id")
    assert skyramp.get_response_value(api_notifications_GET_response, "0.title") == "Skyramp Search Alpha"
    assert skyramp.get_response_value(api_notifications_GET_response, "0.description") == "nightly archive job completed"
    assert skyramp.get_response_value(api_notifications_GET_response, "1") is None

    # Execute Request
    api_notifications_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": ["archive"]}
    )

    # Generated Assertions
    assert api_notifications_GET_1_response.status_code == 200
    assert skyramp.get_response_value(api_notifications_GET_1_response, "0.id") == skyramp.get_response_value(notifications_POST_response, "id")
    assert skyramp.get_response_value(api_notifications_GET_1_response, "0.title") == "Skyramp Search Alpha"
    assert skyramp.get_response_value(api_notifications_GET_1_response, "0.description") == "nightly archive job completed"
    assert skyramp.get_response_value(api_notifications_GET_1_response, "1") is None

    # Execute Request
    api_notifications_GET_2_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": ["NoSuchTermXyz"]}
    )

    # Generated Assertions
    assert api_notifications_GET_2_response.status_code == 200
    assert skyramp.get_response_value(api_notifications_GET_2_response, "0") is None

    # Execute Request
    api_notifications_GET_3_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": [""]}
    )

    # Generated Assertions
    assert api_notifications_GET_3_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_GET_3_response, "message") == "Validation failed"
    assert skyramp.get_response_value(api_notifications_GET_3_response, "errors.0.code") == "too_small"
    assert skyramp.get_response_value(api_notifications_GET_3_response, "errors.0.minimum") == 1
    assert skyramp.get_response_value(api_notifications_GET_3_response, "errors.0.path.0") == "search"
    assert skyramp.get_response_value(api_notifications_GET_3_response, "errors.1") is None

    # Execute Request
    api_notifications_GET_4_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": ["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"]}
    )

    # Generated Assertions
    assert api_notifications_GET_4_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_GET_4_response, "message") == "Validation failed"
    assert skyramp.get_response_value(api_notifications_GET_4_response, "errors.0.code") == "too_big"
    assert skyramp.get_response_value(api_notifications_GET_4_response, "errors.0.maximum") == 255
    assert skyramp.get_response_value(api_notifications_GET_4_response, "errors.0.path.0") == "search"
    assert skyramp.get_response_value(api_notifications_GET_4_response, "errors.1") is None

    # Request Body
    api_notifications_DELETE_request_body = json.dumps({
        "ids": [
            skyramp.get_response_value(notifications_POST_response, "id"),
            skyramp.get_response_value(notifications_POST_1_response, "id")
        ]
    })

    # Execute Request
    api_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=api_notifications_DELETE_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
