# Generated by Skyramp v1.3.44 on 2026-09-12 18:56:19.571811383 +0000 UTC m=+1596.793248376
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notification_statistics_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notification_statistics_lifecycle.json

# Import of required libraries
import skyramp
import os
import time
import re
import json
import uuid


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

UUID_RE = r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
ISO_RE = r"^\d{4}-\d{2}-\d{2}T"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")
    headers["Content-Type"] = "application/json"

    run = uuid.uuid4().hex[:8]

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    user_id = skyramp.get_response_value(me_GET_response, "id")
    assert re.match(UUID_RE, str(user_id), re.IGNORECASE)

    read_at = "2026-09-12T18:00:00.000Z"

    # Baseline counts before this test creates anything
    statistics_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="GET",
        headers=headers
    )
    assert statistics_GET_response.status_code == 200
    baseline_total = skyramp.get_response_value(statistics_GET_response, "total")
    baseline_unread = skyramp.get_response_value(statistics_GET_response, "unread")
    assert isinstance(baseline_total, int)
    assert isinstance(baseline_unread, int)
    assert baseline_total >= 0
    assert 0 <= baseline_unread <= baseline_total

    alpha_title = "testbot-stats-alpha-" + run
    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"userId": user_id, "title": alpha_title}),
        headers=headers
    )
    assert notifications_POST_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_response, "title") == alpha_title
    assert skyramp.get_response_value(notifications_POST_response, "level") == "info"
    assert skyramp.get_response_value(notifications_POST_response, "type") == "Custom"
    assert skyramp.get_response_value(notifications_POST_response, "readAt") is None
    assert re.match(ISO_RE, str(skyramp.get_response_value(notifications_POST_response, "createdAt")))
    alpha_id = skyramp.get_response_value(notifications_POST_response, "id")
    assert re.match(UUID_RE, str(alpha_id), re.IGNORECASE)

    bravo_title = "testbot-stats-bravo-" + run
    notifications_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"userId": user_id, "title": bravo_title}),
        headers=headers
    )
    assert notifications_POST_1_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_1_response, "title") == bravo_title
    assert skyramp.get_response_value(notifications_POST_1_response, "readAt") is None
    bravo_id = skyramp.get_response_value(notifications_POST_1_response, "id")
    assert re.match(UUID_RE, str(bravo_id), re.IGNORECASE)
    assert bravo_id != alpha_id

    # Both new notices are counted, and both are unread
    statistics_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="GET",
        headers=headers
    )
    assert statistics_GET_1_response.status_code == 200
    assert skyramp.get_response_value(statistics_GET_1_response, "total") == baseline_total + 2
    assert skyramp.get_response_value(statistics_GET_1_response, "unread") == baseline_unread + 2

    # Marking one read moves it out of unread without changing total
    notifications_notifications_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/" + str(alpha_id),
        method="PUT",
        body=json.dumps({"readAt": read_at}),
        headers=headers
    )
    assert notifications_notifications_PUT_response.status_code == 200
    assert skyramp.get_response_value(notifications_notifications_PUT_response, "id") == alpha_id
    assert skyramp.get_response_value(notifications_notifications_PUT_response, "title") == alpha_title
    assert skyramp.get_response_value(notifications_notifications_PUT_response, "readAt") == read_at

    statistics_GET_2_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="GET",
        headers=headers
    )
    assert statistics_GET_2_response.status_code == 200
    assert skyramp.get_response_value(statistics_GET_2_response, "total") == baseline_total + 2
    assert skyramp.get_response_value(statistics_GET_2_response, "unread") == baseline_unread + 1

    # Clearing read notifications removes exactly the read ones
    api_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=json.dumps({"read": True}),
        headers=headers
    )
    assert api_notifications_DELETE_response.status_code == 204

    statistics_GET_3_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="GET",
        headers=headers
    )
    assert statistics_GET_3_response.status_code == 200
    total_after_clear = skyramp.get_response_value(statistics_GET_3_response, "total")
    unread_after_clear = skyramp.get_response_value(statistics_GET_3_response, "unread")
    assert unread_after_clear == baseline_unread + 1
    assert total_after_clear == unread_after_clear

    # The notice that was read is gone; the unread one survived
    cleared_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/" + str(alpha_id),
        method="GET",
        headers=headers
    )
    assert cleared_GET_response.status_code == 404
    assert skyramp.get_response_value(cleared_GET_response, "message") == "Notification not found"

    survivor_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/" + str(bravo_id),
        method="GET",
        headers=headers
    )
    assert survivor_GET_response.status_code == 200
    assert skyramp.get_response_value(survivor_GET_response, "id") == bravo_id
    assert skyramp.get_response_value(survivor_GET_response, "title") == bravo_title
    assert skyramp.get_response_value(survivor_GET_response, "readAt") is None

    # Clean up the record this test created
    notifications_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/" + str(bravo_id),
        method="DELETE",
        headers=headers
    )
    assert notifications_notifications_DELETE_response.status_code == 204

    statistics_GET_4_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="GET",
        headers=headers
    )
    assert statistics_GET_4_response.status_code == 200
    assert skyramp.get_response_value(statistics_GET_4_response, "unread") == baseline_unread
    assert skyramp.get_response_value(statistics_GET_4_response, "total") == baseline_unread
