// Generated by Skyramp v1.3.44 on 2026-09-08 21:29:28.725050167 +0000 UTC m=+2580.048089058
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output notification_panel_search.spec.ts \
// 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/immich-testb/immich-testb/.skyramp/notification_panel_search_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:2285");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(277000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => pageErrors.push(error.message));

    await page.goto(`${baseUrl}/auth/logout`);
    await page.evaluate(() => { localStorage.removeItem('appVersion'); return { appVersion: localStorage.getItem('appVersion') }; });
    await page.goto(`${baseUrl}/auth/login`);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@immich.test",
        "password": "password"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/auth/login**");
    await page.getByRole("button", { name: "Login" }).click();
    const response0 = await responsePromise0;

    expect(response0.status()).toBe(201);
    const loginBody = await response0.json();
    expect(getValue(loginBody, "userEmail")).toBe("admin@immich.test");
    expect(getValue(loginBody, "isAdmin")).toBe(true);
    expect(getValue(loginBody, "userId")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(loginBody, "accessToken")).not.toBeNull();

    await page.getByRole("button", { name: "Acknowledge" }).click();
    await page.goto(`${baseUrl}/admin/users`);
    await page.getByRole("link", { name: "Admin" }).click();

    const playwrightRequest1: Record<string, any> = {
        "description": "Nightly archive job completed",
        "title": "Skyramp Backup Finished"
    };

    await page.getByTestId("send-notification-title").fill(getValue(playwrightRequest1, "title"));
    await page.getByTestId("send-notification-description").fill(getValue(playwrightRequest1, "description"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/**/notifications**");
    await page.getByTestId("send-notification-submit").click();
    const response1 = await responsePromise1;

    expect(response1.status()).toBe(201);
    const backupNotification = await response1.json();
    expect(getValue(backupNotification, "id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(backupNotification, "createdAt")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getValue(backupNotification, "title")).toBe("Skyramp Backup Finished");
    expect(getValue(backupNotification, "description")).toBe("Nightly archive job completed");
    expect(getValue(backupNotification, "level")).toBe("info");
    expect(getValue(backupNotification, "type")).toBe("Custom");

    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest2: Record<string, any> = {
        "description": "Library scan aborted early",
        "level": "error",
        "title": "Skyramp Import Failed"
    };

    await page.getByTestId("send-notification-title").fill(getValue(playwrightRequest2, "title"));
    await page.getByTestId("send-notification-description").fill(getValue(playwrightRequest2, "description"));
    await page.getByTestId("send-notification-level").selectOption(getValue(playwrightRequest2, "level"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/api/**/notifications**");
    await page.getByTestId("send-notification-submit").click();
    const response2 = await responsePromise2;

    expect(response2.status()).toBe(201);
    const importNotification = await response2.json();
    expect(getValue(importNotification, "id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(importNotification, "createdAt")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getValue(importNotification, "title")).toBe("Skyramp Import Failed");
    expect(getValue(importNotification, "description")).toBe("Library scan aborted early");
    expect(getValue(importNotification, "level")).toBe("error");
    expect(getValue(importNotification, "type")).toBe("Custom");

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("link", { name: "Immich logo" }).click();
    await page.getByRole("button", { name: "Notifications" }).click();
    await expect(page.getByRole("button", { name: "Skyramp Backup Finished Skyramp Backup Finished Nightly archive job completed" })).toContainText("Skyramp Backup Finished");
    await expect(page.getByRole("button", { name: "Skyramp Import Failed Skyramp Import Failed Library scan aborted early" })).toContainText("Skyramp Import Failed");
    await page.getByTestId("notification-search").fill("Backup");
    await expect(page.getByText("Skyramp Import Failed", { exact: true })).toBeHidden();
    await expect(page.getByTestId("notification-item")).toContainText("Skyramp Backup Finished");
    await page.getByTestId("notification-search").fill("");
    await expect(page.getByRole("button", { name: "Skyramp Import Failed Skyramp Import Failed Library scan aborted early" })).toContainText("Skyramp Import Failed");
    await page.locator("#notification-panel").getByRole("button", { name: "Mark all as read" }).click();
    await page.getByTestId("notification-clear-read").click();
    await expect(page.getByText("Skyramp Backup Finished", { exact: true })).toBeHidden();
    expect(pageErrors).toEqual([]);
});
