// Generated by Skyramp v1.3.44 on 2026-09-08 21:29:34.124715492 +0000 UTC m=+2585.447754383
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output notification_panel_remove_item.spec.ts \
// 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/immich-testb/immich-testb/.skyramp/notification_panel_remove_item_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:2285");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(219000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => pageErrors.push(error.message));

    await page.goto(`${baseUrl}/auth/logout`);
    await page.evaluate(() => { localStorage.removeItem('appVersion'); return { appVersion: localStorage.getItem('appVersion') }; });
    await page.goto(`${baseUrl}/auth/login`);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@immich.test",
        "password": "password"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/auth/login**");
    await page.getByRole("button", { name: "Login" }).click();
    const response0 = await responsePromise0;

    expect(response0.status()).toBe(201);
    const loginBody = await response0.json();
    expect(getValue(loginBody, "userEmail")).toBe("admin@immich.test");
    expect(getValue(loginBody, "isAdmin")).toBe(true);
    expect(getValue(loginBody, "userId")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(loginBody, "accessToken")).not.toBeNull();

    await page.getByRole("button", { name: "Acknowledge" }).click();
    await page.goto(`${baseUrl}/admin/users`);
    await page.getByRole("link", { name: "Admin" }).click();

    const playwrightRequest1: Record<string, any> = {"title": "Skyramp Quota Warning"};

    await page.getByTestId("send-notification-title").fill(getValue(playwrightRequest1, "title"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/**/notifications**");
    await page.getByTestId("send-notification-submit").click();
    const response1 = await responsePromise1;

    expect(response1.status()).toBe(201);
    const quotaNotification = await response1.json();
    expect(getValue(quotaNotification, "id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(quotaNotification, "createdAt")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getValue(quotaNotification, "title")).toBe("Skyramp Quota Warning");
    expect(getValue(quotaNotification, "level")).toBe("info");
    expect(getValue(quotaNotification, "type")).toBe("Custom");

    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest2: Record<string, any> = {"title": "Skyramp Sync Complete"};

    await page.getByTestId("send-notification-title").fill(getValue(playwrightRequest2, "title"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/api/**/notifications**");
    await page.getByTestId("send-notification-submit").click();
    const response2 = await responsePromise2;

    expect(response2.status()).toBe(201);
    const syncNotification = await response2.json();
    expect(getValue(syncNotification, "id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(syncNotification, "createdAt")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getValue(syncNotification, "title")).toBe("Skyramp Sync Complete");
    expect(getValue(syncNotification, "level")).toBe("info");
    expect(getValue(syncNotification, "type")).toBe("Custom");

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("link", { name: "Immich logo" }).click();
    await page.getByRole("button", { name: "Notifications" }).click();
    await expect(page.getByRole("button", { name: "Skyramp Sync Complete Skyramp Sync Complete" })).toContainText("Skyramp Sync Complete");
    await expect(page.getByRole("button", { name: "Skyramp Quota Warning Skyramp Quota Warning" })).toContainText("Skyramp Quota Warning");
    await page.getByTestId("notification-search").fill("Sync Complete");
    await expect(page.getByText("Skyramp Quota Warning", { exact: true })).toBeHidden();
    await page.getByTestId("notification-remove").click();
    await page.getByTestId("notification-search").fill("");
    await expect(page.getByTestId("notification-item")).toContainText("Skyramp Quota Warning");
    await expect(page.getByText("Skyramp Sync Complete", { exact: true })).toBeHidden();
    await page.getByTestId("notification-remove").click();
    expect(pageErrors).toEqual([]);
});
