# Generated by Skyramp v1.3.44 on 2026-09-08 21:29:16.622630635 +0000 UTC m=+2567.945669536
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notification_cross_user_isolation_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notification_cross_user_isolation.json

# Import of required libraries
import skyramp
import json
import os
import re
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(me_GET_response, "id"), re.I)
    assert "@" in skyramp.get_response_value(me_GET_response, "email")
    assert skyramp.get_response_value(me_GET_response, "isAdmin") == True

    # Request Body
    users_POST_request_body = r'''{
        "email": "skyramp.isolation.b@immich.test",
        "name": "Isolation B",
        "password": "Isolation-Pass-123"
    }'''

    # Execute Request
    users_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/users",
        method="POST",
        body=users_POST_request_body,
        headers=headers,
        data_override={"email": skyramp.unique_suffix("skyramp.isolation.b@immich.test")}
    )

    # Generated Assertions
    assert users_POST_response.status_code == 201
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(users_POST_response, "id"), re.I)
    assert "skyramp.isolation.b" in skyramp.get_response_value(users_POST_response, "email")
    assert skyramp.get_response_value(users_POST_response, "name") == "Isolation B"
    assert skyramp.get_response_value(users_POST_response, "isAdmin") == False
    assert skyramp.get_response_value(users_POST_response, "id") != skyramp.get_response_value(me_GET_response, "id")

    # Request Body
    notifications_POST_request_body = r'''{
        "title": "Skyramp Foreign Notice",
        "userId": "f1a85c6c-91d7-4ea3-8265-d37e4b9e1fa8"
    }'''

    # Execute Request
    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_request_body,
        headers=headers,
        data_override={"userId": skyramp.get_response_value(users_POST_response, "id")}
    )

    # Generated Assertions
    assert notifications_POST_response.status_code == 201
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(notifications_POST_response, "id"), re.I)
    assert re.match(r"^\d{4}-\d{2}-\d{2}T", skyramp.get_response_value(notifications_POST_response, "createdAt"))
    assert skyramp.get_response_value(notifications_POST_response, "title") == "Skyramp Foreign Notice"
    assert skyramp.get_response_value(notifications_POST_response, "level") == "info"
    assert skyramp.get_response_value(notifications_POST_response, "type") == "Custom"

    # Request Body
    notifications_POST_1_request_body = r'''{
        "title": "Skyramp Own Notice",
        "userId": "1293a3b5-2b75-4f56-9dac-244b2996cf86"
    }'''

    # Execute Request
    notifications_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_1_request_body,
        headers=headers,
        data_override={"userId": skyramp.get_response_value(me_GET_response, "id")}
    )

    # Generated Assertions
    assert notifications_POST_1_response.status_code == 201
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(notifications_POST_1_response, "id"), re.I)
    assert skyramp.get_response_value(notifications_POST_1_response, "title") == "Skyramp Own Notice"
    assert skyramp.get_response_value(notifications_POST_1_response, "id") != skyramp.get_response_value(notifications_POST_response, "id")

    # Execute Request
    statistics_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert statistics_GET_response.status_code == 200
    assert skyramp.get_response_value(statistics_GET_response, "total") == 1
    assert skyramp.get_response_value(statistics_GET_response, "unread") == 1

    # Execute Request
    api_notifications_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_GET_response.status_code == 200
    assert skyramp.get_response_value(api_notifications_GET_response, "0.id") == skyramp.get_response_value(notifications_POST_1_response, "id")
    assert skyramp.get_response_value(api_notifications_GET_response, "0.title") == "Skyramp Own Notice"
    assert skyramp.get_response_value(api_notifications_GET_response, "1") is None

    # Execute Request
    notifications_notifications_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="GET",
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_response, "id")}
    )

    # Generated Assertions
    assert notifications_notifications_GET_response.status_code == 400
    assert skyramp.get_response_value(notifications_notifications_GET_response, "message") == "Not found or no notification.read access"
    assert skyramp.get_response_value(notifications_notifications_GET_response, "title") is None
    assert skyramp.get_response_value(notifications_notifications_GET_response, "id") is None

    # Request Body
    notifications_notifications_PUT_request_body = r'''{
        "readAt": "2026-09-08T21:00:00.000Z"
    }'''

    # Execute Request
    notifications_notifications_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="PUT",
        body=notifications_notifications_PUT_request_body,
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_response, "id")}
    )

    # Generated Assertions
    assert notifications_notifications_PUT_response.status_code == 400
    assert skyramp.get_response_value(notifications_notifications_PUT_response, "message") == "Not found or no notification.update access"
    assert skyramp.get_response_value(notifications_notifications_PUT_response, "title") is None

    # Execute Request
    notifications_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="DELETE",
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_response, "id")}
    )

    # Generated Assertions
    assert notifications_notifications_DELETE_response.status_code == 400
    assert skyramp.get_response_value(notifications_notifications_DELETE_response, "message") == "Not found or no notification.delete access"

    # Request Body
    api_notifications_DELETE_request_body = json.dumps({
        "ids": [
            skyramp.get_response_value(notifications_POST_1_response, "id")
        ]
    })

    # Execute Request
    api_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=api_notifications_DELETE_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_DELETE_response.status_code == 204

    # Request Body
    users_users_DELETE_request_body = r'''{
        "force": true
    }'''

    # Execute Request
    users_users_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/users/{users}",
        method="DELETE",
        body=users_users_DELETE_request_body,
        headers=headers,
        path_params={"users": skyramp.get_response_value(users_POST_response, "id")}
    )

    # Generated Assertions
    assert users_users_DELETE_response.status_code == 200
    assert skyramp.get_response_value(users_users_DELETE_response, "id") == skyramp.get_response_value(users_POST_response, "id")


if __name__ == "__main__":
    test_integration()
