// Generated by Skyramp v1.3.44 on 2026-09-08 21:35:45.102849352 +0000 UTC m=+1986.475957675
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output notification_search_and_clear_read.spec.ts \
// 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/immich-testb/immich-testb/.skyramp/notification_search_clear_read_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:2285");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(339000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => pageErrors.push(error.message));

    await page.goto(`${baseUrl}/auth/login`);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@immich.test",
        "password": "password"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/auth/login**");
    await page.getByRole("button", { name: "Login" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(201);
    const loginBody = await response0.json();
    expect(loginBody.userEmail).toBe(getValue(playwrightRequest0, "email"));
    expect(loginBody.isAdmin).toBe(true);

    await page.getByRole("button", { name: "Acknowledge" }).click();
    await page.goto(`${baseUrl}/admin/users`);
    await page.getByRole("link", { name: "Admin" }).click();

    const playwrightRequest1: Record<string, any> = {"title": "Zebra Notice"};

    await page.getByTestId("send-notification-title").fill(getValue(playwrightRequest1, "title"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/**/notifications**");
    await page.getByTestId("send-notification-submit").click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(201);
    const zebraNotification = await response1.json();
    expect(zebraNotification.title).toBe(getValue(playwrightRequest1, "title"));
    expect(zebraNotification.level).toBe("info");
    expect(zebraNotification.type).toBe("Custom");

    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest2: Record<string, any> = {"title": "Quokka Notice"};

    await page.getByTestId("send-notification-title").fill(getValue(playwrightRequest2, "title"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/api/**/notifications**");
    await page.getByTestId("send-notification-submit").click();
    const response2 = await responsePromise2;
    expect(response2.status()).toBe(201);
    const quokkaNotification = await response2.json();
    expect(quokkaNotification.title).toBe(getValue(playwrightRequest2, "title"));
    expect(quokkaNotification.level).toBe("info");
    expect(quokkaNotification.type).toBe("Custom");

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto(`${baseUrl}/photos`);
    await page.getByRole("button", { name: "Notifications" }).click();
    await expect(page.getByTestId("notification-unread-badge")).toHaveText("2");
    await expect(page.getByTestId("notification-clear-read")).toBeDisabled();
    await page.getByTestId("notification-search").fill("Zebra");
    await expect(page.getByTestId("notification-item")).toHaveCount(1);
    await expect(page.getByTestId("notification-item")).toContainText("Zebra Notice");
    await expect(page.getByText("Quokka Notice", { exact: true })).toBeHidden();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise3 = page.waitForResponse("**/api/notifications/**");
    await page.getByTestId("notification-item").click();
    const response3 = await responsePromise3;
    expect(response3.status()).toBe(200);
    const markedRead = await response3.json();
    expect(markedRead.id).toBe(zebraNotification.id);
    expect(markedRead.title).toBe("Zebra Notice");
    expect(markedRead.readAt).toMatch(/^\d{4}-\d{2}-\d{2}T/);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByTestId("notification-unread-badge")).toHaveText("1");
    await expect(page.getByTestId("notification-clear-read")).toBeEnabled();
    await page.getByTestId("notification-show-read").click();
    await expect(page.getByTestId("notification-item")).toHaveCount(1);
    await expect(page.getByTestId("notification-item")).toContainText("Zebra Notice");
    await expect(page.getByTestId("notification-item")).toHaveAttribute("data-read", "true");
    await page.getByTestId("notification-clear-read").click();
    await expect(page.getByText("Zebra Notice", { exact: true })).toBeHidden();
    await expect(page.getByTestId("notification-clear-read")).toBeDisabled();
    await expect(page.getByTestId("notification-unread-badge")).toHaveText("1");
    await page.getByTestId("notification-search").fill("Quokka");
    await expect(page.getByTestId("notification-item")).toHaveCount(1);
    await expect(page.getByTestId("notification-item")).toContainText("Quokka Notice");
    await expect(page.getByTestId("notification-item")).toHaveAttribute("data-read", "false");
    await page.getByTestId("notification-remove").click();
    await expect(page.getByTestId("notification-unread-badge")).toBeHidden();
    await expect(page.getByTestId("notification-item")).toHaveCount(0);
    await expect(page.getByText("No notifications", { exact: true })).toBeVisible();
    expect(pageErrors).toEqual([]);
});
