# Generated by Skyramp v1.3.44 on 2026-09-12 18:56:41.744562731 +0000 UTC m=+1618.965999734
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notification_update_after_clear_read_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notification_update_after_clear_read.json

# Import of required libraries
import skyramp
import os
import time
import re
import json
import uuid


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

UUID_RE = r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
ISO_RE = r"^\d{4}-\d{2}-\d{2}T"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")
    headers["Content-Type"] = "application/json"

    run = uuid.uuid4().hex[:8]

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    user_id = skyramp.get_response_value(me_GET_response, "id")
    assert re.match(UUID_RE, str(user_id), re.IGNORECASE)

    read_at = "2026-09-12T18:00:00.000Z"
    title = "testbot-stale-update-" + run

    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"userId": user_id, "title": title}),
        headers=headers
    )
    assert notifications_POST_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_response, "title") == title
    notification_id = skyramp.get_response_value(notifications_POST_response, "id")
    assert re.match(UUID_RE, str(notification_id), re.IGNORECASE)

    # While the notice exists, updating it is accepted
    notifications_notifications_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/" + str(notification_id),
        method="PUT",
        body=json.dumps({"readAt": read_at}),
        headers=headers
    )
    assert notifications_notifications_PUT_response.status_code == 200
    assert skyramp.get_response_value(notifications_notifications_PUT_response, "id") == notification_id
    assert skyramp.get_response_value(notifications_notifications_PUT_response, "title") == title
    assert skyramp.get_response_value(notifications_notifications_PUT_response, "readAt") == read_at

    # Clear read removes it
    api_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=json.dumps({"read": True}),
        headers=headers
    )
    assert api_notifications_DELETE_response.status_code == 204

    # A fetch of the cleared notice answers 404
    notifications_notifications_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/" + str(notification_id),
        method="GET",
        headers=headers
    )
    assert notifications_notifications_GET_response.status_code == 404
    assert skyramp.get_response_value(notifications_notifications_GET_response, "message") == "Notification not found"

    # An update of the cleared notice must answer the same way, not fail with a server error
    notifications_notifications_PUT_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/" + str(notification_id),
        method="PUT",
        body=json.dumps({"readAt": None}),
        headers=headers
    )
    assert notifications_notifications_PUT_1_response.status_code == 404
    assert skyramp.get_response_value(notifications_notifications_PUT_1_response, "message") == "Notification not found"
    assert skyramp.get_response_value(notifications_notifications_PUT_1_response, "id") is None
