# Generated by Skyramp v1.3.44 on 2026-09-08 21:14:15.185033391 +0000 UTC m=+1541.769323127
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notification_statistics_counts_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notification_statistics_counts.json

# Import of required libraries
import skyramp
import os
import json
import re
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    assert skyramp.get_response_value(me_GET_response, "isAdmin") is True

    # Execute Request
    statistics_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert statistics_GET_response.status_code == 200
    baseline_total = skyramp.get_response_value(statistics_GET_response, "total")
    baseline_unread = skyramp.get_response_value(statistics_GET_response, "unread")
    assert isinstance(baseline_total, int) and baseline_total >= 0
    assert isinstance(baseline_unread, int) and baseline_unread >= 0
    assert baseline_unread <= baseline_total

    # Request Body
    notifications_POST_request_body = r'''{
        "level": "info",
        "title": "Skyramp statistics probe one",
        "userId": "6ecb082e-4c2a-4668-ab6d-0bd4091f9c13"
    }'''

    # Execute Request
    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_request_body,
        headers=headers,
        data_override={"userId": skyramp.get_response_value(me_GET_response, "id")}
    )

    # Generated Assertions
    assert notifications_POST_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_response, "title") == "Skyramp statistics probe one"
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(notifications_POST_response, "id"), re.I)

    # Request Body
    notifications_POST_1_request_body = r'''{
        "level": "info",
        "title": "Skyramp statistics probe two",
        "userId": "6ecb082e-4c2a-4668-ab6d-0bd4091f9c13"
    }'''

    # Execute Request
    notifications_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_1_request_body,
        headers=headers,
        data_override={"userId": skyramp.get_response_value(me_GET_response, "id")}
    )

    # Generated Assertions
    assert notifications_POST_1_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_1_response, "title") == "Skyramp statistics probe two"
    assert skyramp.get_response_value(notifications_POST_1_response, "id") != skyramp.get_response_value(notifications_POST_response, "id")

    # Execute Request
    statistics_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert statistics_GET_1_response.status_code == 200
    assert skyramp.get_response_value(statistics_GET_1_response, "total") == baseline_total + 2
    assert skyramp.get_response_value(statistics_GET_1_response, "unread") == baseline_unread + 2

    # Request Body
    notifications_notifications_PUT_request_body = r'''{
        "readAt": "2026-09-08T21:00:00.000Z"
    }'''

    # Execute Request
    notifications_notifications_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="PUT",
        body=notifications_notifications_PUT_request_body,
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_response, "id")},
        data_override={"readAt": skyramp.get_response_value(notifications_POST_response, "createdAt")}
    )

    # Generated Assertions
    assert notifications_notifications_PUT_response.status_code == 200
    assert skyramp.get_response_value(notifications_notifications_PUT_response, "id") == skyramp.get_response_value(notifications_POST_response, "id")
    assert re.match(r"^\d{4}-\d{2}-\d{2}T", skyramp.get_response_value(notifications_notifications_PUT_response, "readAt"))

    # Execute Request
    statistics_GET_2_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert statistics_GET_2_response.status_code == 200
    assert skyramp.get_response_value(statistics_GET_2_response, "total") == baseline_total + 2
    assert skyramp.get_response_value(statistics_GET_2_response, "unread") == baseline_unread + 1

    # Request Body
    statistics_POST_request_body = r'''{
        "total": 0,
        "unread": 0
    }'''

    # Execute Request
    statistics_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="POST",
        body=statistics_POST_request_body,
        headers=headers,
        data_override={
            "total": skyramp.get_response_value(statistics_GET_response, "total"),
            "unread": skyramp.get_response_value(statistics_GET_response, "unread")
        }
    )

    # Generated Assertions
    assert statistics_POST_response.status_code == 404
    assert skyramp.get_response_value(statistics_POST_response, "message") == "Cannot POST /api/notifications/statistics"

    # Request Body
    api_notifications_DELETE_request_body = json.dumps({
        "ids": [
            skyramp.get_response_value(notifications_POST_response, "id"),
            skyramp.get_response_value(notifications_POST_1_response, "id")
        ]
    })

    # Execute Request
    api_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=api_notifications_DELETE_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_DELETE_response.status_code == 204

    # Execute Request
    statistics_GET_3_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert statistics_GET_3_response.status_code == 200
    assert skyramp.get_response_value(statistics_GET_3_response, "total") == baseline_total
    assert skyramp.get_response_value(statistics_GET_3_response, "unread") == baseline_unread


if __name__ == "__main__":
    test_integration()
