# Generated by Skyramp v1.3.44 on 2026-09-08 21:14:29.9488101 +0000 UTC m=+1556.533099835
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notification_bulk_cap_500_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notification_bulk_cap_500.json

# Import of required libraries
import skyramp
import os
import json
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

# A well-formed uuid that belongs to no notification. Repeating it makes the id list
# as long as the cap probe needs while leaving the caller's notifications untouched,
# because the access check collapses the list to a single unknown id.
MISSING_ID = "9c1f2a54-7b0e-4d3a-8f61-2ab5c7d94e08"
READ_AT = "2026-09-08T21:00:00.000Z"


def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    assert skyramp.get_response_value(me_GET_response, "isAdmin") is True

    # Request Body
    notifications_POST_request_body = r'''{
        "level": "info",
        "title": "Skyramp bulk cap probe",
        "userId": "6ecb082e-4c2a-4668-ab6d-0bd4091f9c13"
    }'''

    # Execute Request
    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_request_body,
        headers=headers,
        data_override={"userId": skyramp.get_response_value(me_GET_response, "id")}
    )

    # Generated Assertions
    assert notifications_POST_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_response, "title") == "Skyramp bulk cap probe"

    # Request Body
    api_notifications_PUT_request_body = json.dumps({
        "ids": [skyramp.get_response_value(notifications_POST_response, "id")],
        "readAt": READ_AT
    })

    # Execute Request
    api_notifications_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="PUT",
        body=api_notifications_PUT_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_PUT_response.status_code == 204

    # Request Body
    api_notifications_PUT_1_request_body = json.dumps({
        "ids": [MISSING_ID] * 101,
        "readAt": READ_AT
    })

    # Execute Request
    api_notifications_PUT_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="PUT",
        body=api_notifications_PUT_1_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_PUT_1_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_PUT_1_response, "message") == "Not found or no notification.update access"

    # Request Body
    api_notifications_PUT_2_request_body = json.dumps({
        "ids": [MISSING_ID] * 501,
        "readAt": READ_AT
    })

    # Execute Request
    api_notifications_PUT_2_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="PUT",
        body=api_notifications_PUT_2_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_PUT_2_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_PUT_2_response, "message") == "Cannot update more than 500 notifications at once"

    # Request Body
    api_notifications_PUT_3_request_body = r'''{
        "readAt": "2026-09-08T21:00:00.000Z"
    }'''

    # Execute Request
    api_notifications_PUT_3_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="PUT",
        body=api_notifications_PUT_3_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_PUT_3_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_PUT_3_response, "message") == "Validation failed"
    assert skyramp.get_response_value(api_notifications_PUT_3_response, "errors.0.path.0") == "ids"
    assert skyramp.get_response_value(api_notifications_PUT_3_response, "errors.1") is None

    # Request Body
    api_notifications_DELETE_request_body = json.dumps({
        "ids": [skyramp.get_response_value(notifications_POST_response, "id")]
    })

    # Execute Request
    api_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=api_notifications_DELETE_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
