# Generated by Skyramp v1.3.44 on 2026-09-08 21:35:24.767732842 +0000 UTC m=+1966.140841175
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notifications_get_and_search_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notifications_get_and_search.json

# Import of required libraries
import skyramp
import os
import re
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    search = "nomatch-zzz"

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(me_GET_response, "id"), re.I)
    assert "@" in skyramp.get_response_value(me_GET_response, "email")
    caller_id = skyramp.get_response_value(me_GET_response, "id")

    # Request Body
    notifications_POST_request_body = r'''{
        "description": "searchable haystack marker",
        "title": "Skyramp Fetch Target",
        "userId": "aaaaaaa1-1a2b-4c3d-8e4f-0a0000000001"
    }'''

    # Execute Request
    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_request_body,
        headers=headers,
        data_override={"userId": caller_id}
    )

    # Generated Assertions
    assert notifications_POST_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_response, "title") == "Skyramp Fetch Target"
    assert skyramp.get_response_value(notifications_POST_response, "description") == "searchable haystack marker"
    assert skyramp.get_response_value(notifications_POST_response, "level") == "info"
    assert skyramp.get_response_value(notifications_POST_response, "type") == "Custom"
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(notifications_POST_response, "id"), re.I)
    assert re.match(r"^\d{4}-\d{2}-\d{2}T", skyramp.get_response_value(notifications_POST_response, "createdAt"))
    created_id = skyramp.get_response_value(notifications_POST_response, "id")

    # Execute Request
    notifications_notifications_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="GET",
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_response, "id")}
    )

    # Generated Assertions
    assert notifications_notifications_GET_response.status_code == 200
    assert skyramp.get_response_value(notifications_notifications_GET_response, "id") == created_id
    assert skyramp.get_response_value(notifications_notifications_GET_response, "title") == "Skyramp Fetch Target"
    assert skyramp.get_response_value(notifications_notifications_GET_response, "description") == "searchable haystack marker"
    assert skyramp.get_response_value(notifications_notifications_GET_response, "level") == "info"
    assert skyramp.get_response_value(notifications_notifications_GET_response, "type") == "Custom"

    # Execute Request
    api_notifications_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": ["haystack"]}
    )

    # Generated Assertions
    assert api_notifications_GET_response.status_code == 200
    assert len(skyramp.get_response_value(api_notifications_GET_response, "")) == 1
    assert skyramp.get_response_value(api_notifications_GET_response, "0.id") == created_id
    assert skyramp.get_response_value(api_notifications_GET_response, "0.title") == "Skyramp Fetch Target"
    assert skyramp.get_response_value(api_notifications_GET_response, "0.description") == "searchable haystack marker"
    assert skyramp.get_response_value(api_notifications_GET_response, "1") is None

    # Execute Request
    api_notifications_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": ["nomatch-zzz"]}
    )

    # Generated Assertions
    assert api_notifications_GET_1_response.status_code == 200
    assert len(skyramp.get_response_value(api_notifications_GET_1_response, "")) == 0
    assert skyramp.get_response_value(api_notifications_GET_1_response, "0") is None

    # Execute Request
    notifications_11111111_2222_4333_8444_555555555555_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/11111111-2222-4333-8444-555555555555",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert notifications_11111111_2222_4333_8444_555555555555_GET_response.status_code == 404
    assert skyramp.get_response_value(notifications_11111111_2222_4333_8444_555555555555_GET_response, "message") == "Notification not found"

    # Execute Request
    notifications_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="DELETE",
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_response, "id")}
    )

    # Generated Assertions
    assert notifications_notifications_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
