// Generated by Skyramp v1.3.44 on 2026-09-12 18:56:51.303963268 +0000 UTC m=+1628.525400281
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output notification_clear_read.spec.ts \
// 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/immich-testb/immich-testb/.skyramp/notification_clear_read_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, uniqueSuffix, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:2285");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(164000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Run-unique value(s) for unique-constrained create field(s): keeps this test idempotent across re-runs
    const uniqueSendNotificationTitle = uniqueSuffix("");

    await page.goto(`${baseUrl}/auth/logout`);
    await page.goto(`${baseUrl}/auth/login`);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@immich.test",
        "password": "EvalPass123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/auth/login**");
    await page.getByRole("button", { name: "Login" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(201);

    await page.goto(`${baseUrl}/admin/users`);
    await page.getByRole("link", { name: "Immich Admin" }).click();

    const playwrightRequest1: Record<string, any> = {"title": "Testbot notice bravo"};

    await page.getByTestId("send-notification-title").fill(uniqueSendNotificationTitle);
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/**/notifications**");
    await page.getByTestId("send-notification-submit").click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(201);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto(`${baseUrl}/photos`);
    await page.getByRole("button", { name: "Notifications" }).click();
    await expect(page.getByTestId("notification-clear-read")).toBeDisabled();
    await page.getByRole("button", { name: "Mark all as read" }).click();
    await expect(page.getByTestId("notification-clear-read")).toBeEnabled();
    await page.getByTestId("notification-show-read").click();
    await expect(page.getByTestId("notification-item")).toContainText(uniqueSendNotificationTitle);
    await page.getByTestId("notification-clear-read").click();
    await expect(page.getByTestId("notification-item")).toHaveCount(0);
    await expect(page.getByTestId("notification-show-read")).toBeChecked();
    await expect(page.getByTestId("notification-clear-read")).toBeDisabled();
});
