# Generated by Skyramp v1.3.44 on 2026-09-08 21:35:18.120295444 +0000 UTC m=+1959.493403767
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notifications_clear_read_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notifications_clear_read_lifecycle.json

# Import of required libraries
import skyramp
import json
import os
import re
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(me_GET_response, "id"), re.I)
    assert "@" in skyramp.get_response_value(me_GET_response, "email")
    caller_id = skyramp.get_response_value(me_GET_response, "id")

    # Execute Request
    statistics_GET_baseline_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert statistics_GET_baseline_response.status_code == 200
    baseline_total = skyramp.get_response_value(statistics_GET_baseline_response, "total")
    baseline_unread = skyramp.get_response_value(statistics_GET_baseline_response, "unread")
    assert isinstance(baseline_total, int) and baseline_total >= 0
    assert isinstance(baseline_unread, int) and 0 <= baseline_unread <= baseline_total

    # Request Body
    notifications_POST_request_body = r'''{
        "title": "Clear Read Target",
        "userId": "aaaaaaa1-1a2b-4c3d-8e4f-0a0000000001"
    }'''

    # Execute Request
    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_request_body,
        headers=headers,
        data_override={"userId": caller_id}
    )

    # Generated Assertions
    assert notifications_POST_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_response, "title") == "Clear Read Target"
    assert skyramp.get_response_value(notifications_POST_response, "level") == "info"
    assert skyramp.get_response_value(notifications_POST_response, "type") == "Custom"
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(notifications_POST_response, "id"), re.I)
    assert re.match(r"^\d{4}-\d{2}-\d{2}T", skyramp.get_response_value(notifications_POST_response, "createdAt"))
    assert skyramp.get_response_value(notifications_POST_response, "readAt") is None
    target_id = skyramp.get_response_value(notifications_POST_response, "id")

    # Request Body
    notifications_POST_1_request_body = r'''{
        "title": "Clear Read Survivor",
        "userId": "aaaaaaa1-1a2b-4c3d-8e4f-0a0000000001"
    }'''

    # Execute Request
    notifications_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_1_request_body,
        headers=headers,
        data_override={"userId": caller_id}
    )

    # Generated Assertions
    assert notifications_POST_1_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_1_response, "title") == "Clear Read Survivor"
    assert skyramp.get_response_value(notifications_POST_1_response, "level") == "info"
    assert skyramp.get_response_value(notifications_POST_1_response, "type") == "Custom"
    survivor_id = skyramp.get_response_value(notifications_POST_1_response, "id")
    assert survivor_id != target_id

    # Request Body
    api_notifications_PUT_request_body = json.dumps({"ids": [target_id], "readAt": "2026-09-08T12:00:00.000Z"})

    # Execute Request
    api_notifications_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="PUT",
        body=api_notifications_PUT_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_PUT_response.status_code == 204

    # Execute Request
    statistics_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert statistics_GET_response.status_code == 200
    assert skyramp.get_response_value(statistics_GET_response, "total") == baseline_total + 2
    assert skyramp.get_response_value(statistics_GET_response, "unread") == baseline_unread + 1

    # Request Body
    api_notifications_DELETE_request_body = r'''{
        "read": true
    }'''

    # Execute Request
    api_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=api_notifications_DELETE_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_DELETE_response.status_code == 204

    # Execute Request
    notifications_notifications_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="GET",
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_response, "id")}
    )

    # Generated Assertions
    assert notifications_notifications_GET_response.status_code == 404
    assert skyramp.get_response_value(notifications_notifications_GET_response, "message") == "Notification not found"

    # Execute Request
    notifications_notifications_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="GET",
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_1_response, "id")}
    )

    # Generated Assertions
    assert notifications_notifications_GET_1_response.status_code == 200
    assert skyramp.get_response_value(notifications_notifications_GET_1_response, "id") == survivor_id
    assert skyramp.get_response_value(notifications_notifications_GET_1_response, "title") == "Clear Read Survivor"
    assert skyramp.get_response_value(notifications_notifications_GET_1_response, "readAt") is None

    # Execute Request
    statistics_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert statistics_GET_1_response.status_code == 200
    assert skyramp.get_response_value(statistics_GET_1_response, "total") == baseline_total + 1
    assert skyramp.get_response_value(statistics_GET_1_response, "unread") == baseline_unread + 1

    # Execute Request
    notifications_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="DELETE",
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_1_response, "id")}
    )

    # Generated Assertions
    assert notifications_notifications_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
