# Generated by Skyramp v1.3.44 on 2026-09-08 21:35:31.100869668 +0000 UTC m=+1972.473977991
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notifications_input_rejections_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notifications_input_rejections.json

# Import of required libraries
import skyramp
import os
import re
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(me_GET_response, "id"), re.I)
    assert "@" in skyramp.get_response_value(me_GET_response, "email")
    caller_id = skyramp.get_response_value(me_GET_response, "id")

    # Request Body
    notifications_POST_request_body = r'''{
        "title": "Ghost Recipient",
        "userId": "11111111-2222-4333-8444-555555555555"
    }'''

    # Execute Request
    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert notifications_POST_response.status_code == 400
    assert skyramp.get_response_value(notifications_POST_response, "message") == "User not found"
    assert skyramp.get_response_value(notifications_POST_response, "id") is None

    # Request Body
    notifications_POST_1_request_body = r'''{
        "title": "   ",
        "userId": "aaaaaaa1-1a2b-4c3d-8e4f-0a0000000001"
    }'''

    # Execute Request
    notifications_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_1_request_body,
        headers=headers,
        data_override={"userId": caller_id}
    )

    # Generated Assertions
    assert notifications_POST_1_response.status_code == 400
    assert skyramp.get_response_value(notifications_POST_1_response, "message") == "Validation failed"
    assert skyramp.get_response_value(notifications_POST_1_response, "errors.0.path.0") == "title"
    assert skyramp.get_response_value(notifications_POST_1_response, "errors.0.code") == "too_small"
    assert skyramp.get_response_value(notifications_POST_1_response, "errors.0.minimum") == 1
    assert skyramp.get_response_value(notifications_POST_1_response, "errors.1") is None

    # Request Body
    notifications_POST_2_request_body = r'''{
        "userId": "aaaaaaa1-1a2b-4c3d-8e4f-0a0000000001"
    }'''

    # Execute Request
    notifications_POST_2_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_2_request_body,
        headers=headers,
        data_override={"userId": caller_id}
    )

    # Generated Assertions
    assert notifications_POST_2_response.status_code == 400
    assert skyramp.get_response_value(notifications_POST_2_response, "message") == "Validation failed"
    assert skyramp.get_response_value(notifications_POST_2_response, "errors.0.path.0") == "title"
    assert skyramp.get_response_value(notifications_POST_2_response, "errors.1") is None

    # Execute Request
    api_notifications_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": [""]}
    )

    # Generated Assertions
    assert api_notifications_GET_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_GET_response, "message") == "Validation failed"
    assert skyramp.get_response_value(api_notifications_GET_response, "errors.0.path.0") == "search"
    assert skyramp.get_response_value(api_notifications_GET_response, "errors.0.code") == "too_small"
    assert skyramp.get_response_value(api_notifications_GET_response, "errors.0.minimum") == 1
    assert skyramp.get_response_value(api_notifications_GET_response, "errors.1") is None

    # Request Body
    api_notifications_PUT_request_body = r'''{
        "ids": [
            "00000001-1a2b-4c3d-8e4f-0b0000000001",
            "00000002-1a2b-4c3d-8e4f-0b0000000002",
            "00000003-1a2b-4c3d-8e4f-0b0000000003",
            "00000004-1a2b-4c3d-8e4f-0b0000000004",
            "00000005-1a2b-4c3d-8e4f-0b0000000005",
            "00000006-1a2b-4c3d-8e4f-0b0000000006",
            "00000007-1a2b-4c3d-8e4f-0b0000000007",
            "00000008-1a2b-4c3d-8e4f-0b0000000008",
            "00000009-1a2b-4c3d-8e4f-0b0000000009",
            "0000000a-1a2b-4c3d-8e4f-0b000000000a",
            "0000000b-1a2b-4c3d-8e4f-0b000000000b",
            "0000000c-1a2b-4c3d-8e4f-0b000000000c",
            "0000000d-1a2b-4c3d-8e4f-0b000000000d",
            "0000000e-1a2b-4c3d-8e4f-0b000000000e",
            "0000000f-1a2b-4c3d-8e4f-0b000000000f",
            "00000010-1a2b-4c3d-8e4f-0b0000000010",
            "00000011-1a2b-4c3d-8e4f-0b0000000011",
            "00000012-1a2b-4c3d-8e4f-0b0000000012",
            "00000013-1a2b-4c3d-8e4f-0b0000000013",
            "00000014-1a2b-4c3d-8e4f-0b0000000014",
            "00000015-1a2b-4c3d-8e4f-0b0000000015",
            "00000016-1a2b-4c3d-8e4f-0b0000000016",
            "00000017-1a2b-4c3d-8e4f-0b0000000017",
            "00000018-1a2b-4c3d-8e4f-0b0000000018",
            "00000019-1a2b-4c3d-8e4f-0b0000000019",
            "0000001a-1a2b-4c3d-8e4f-0b000000001a",
            "0000001b-1a2b-4c3d-8e4f-0b000000001b",
            "0000001c-1a2b-4c3d-8e4f-0b000000001c",
            "0000001d-1a2b-4c3d-8e4f-0b000000001d",
            "0000001e-1a2b-4c3d-8e4f-0b000000001e",
            "0000001f-1a2b-4c3d-8e4f-0b000000001f",
            "00000020-1a2b-4c3d-8e4f-0b0000000020",
            "00000021-1a2b-4c3d-8e4f-0b0000000021",
            "00000022-1a2b-4c3d-8e4f-0b0000000022",
            "00000023-1a2b-4c3d-8e4f-0b0000000023",
            "00000024-1a2b-4c3d-8e4f-0b0000000024",
            "00000025-1a2b-4c3d-8e4f-0b0000000025",
            "00000026-1a2b-4c3d-8e4f-0b0000000026",
            "00000027-1a2b-4c3d-8e4f-0b0000000027",
            "00000028-1a2b-4c3d-8e4f-0b0000000028",
            "00000029-1a2b-4c3d-8e4f-0b0000000029",
            "0000002a-1a2b-4c3d-8e4f-0b000000002a",
            "0000002b-1a2b-4c3d-8e4f-0b000000002b",
            "0000002c-1a2b-4c3d-8e4f-0b000000002c",
            "0000002d-1a2b-4c3d-8e4f-0b000000002d",
            "0000002e-1a2b-4c3d-8e4f-0b000000002e",
            "0000002f-1a2b-4c3d-8e4f-0b000000002f",
            "00000030-1a2b-4c3d-8e4f-0b0000000030",
            "00000031-1a2b-4c3d-8e4f-0b0000000031",
            "00000032-1a2b-4c3d-8e4f-0b0000000032",
            "00000033-1a2b-4c3d-8e4f-0b0000000033",
            "00000034-1a2b-4c3d-8e4f-0b0000000034",
            "00000035-1a2b-4c3d-8e4f-0b0000000035",
            "00000036-1a2b-4c3d-8e4f-0b0000000036",
            "00000037-1a2b-4c3d-8e4f-0b0000000037",
            "00000038-1a2b-4c3d-8e4f-0b0000000038",
            "00000039-1a2b-4c3d-8e4f-0b0000000039",
            "0000003a-1a2b-4c3d-8e4f-0b000000003a",
            "0000003b-1a2b-4c3d-8e4f-0b000000003b",
            "0000003c-1a2b-4c3d-8e4f-0b000000003c",
            "0000003d-1a2b-4c3d-8e4f-0b000000003d",
            "0000003e-1a2b-4c3d-8e4f-0b000000003e",
            "0000003f-1a2b-4c3d-8e4f-0b000000003f",
            "00000040-1a2b-4c3d-8e4f-0b0000000040",
            "00000041-1a2b-4c3d-8e4f-0b0000000041",
            "00000042-1a2b-4c3d-8e4f-0b0000000042",
            "00000043-1a2b-4c3d-8e4f-0b0000000043",
            "00000044-1a2b-4c3d-8e4f-0b0000000044",
            "00000045-1a2b-4c3d-8e4f-0b0000000045",
            "00000046-1a2b-4c3d-8e4f-0b0000000046",
            "00000047-1a2b-4c3d-8e4f-0b0000000047",
            "00000048-1a2b-4c3d-8e4f-0b0000000048",
            "00000049-1a2b-4c3d-8e4f-0b0000000049",
            "0000004a-1a2b-4c3d-8e4f-0b000000004a",
            "0000004b-1a2b-4c3d-8e4f-0b000000004b",
            "0000004c-1a2b-4c3d-8e4f-0b000000004c",
            "0000004d-1a2b-4c3d-8e4f-0b000000004d",
            "0000004e-1a2b-4c3d-8e4f-0b000000004e",
            "0000004f-1a2b-4c3d-8e4f-0b000000004f",
            "00000050-1a2b-4c3d-8e4f-0b0000000050",
            "00000051-1a2b-4c3d-8e4f-0b0000000051",
            "00000052-1a2b-4c3d-8e4f-0b0000000052",
            "00000053-1a2b-4c3d-8e4f-0b0000000053",
            "00000054-1a2b-4c3d-8e4f-0b0000000054",
            "00000055-1a2b-4c3d-8e4f-0b0000000055",
            "00000056-1a2b-4c3d-8e4f-0b0000000056",
            "00000057-1a2b-4c3d-8e4f-0b0000000057",
            "00000058-1a2b-4c3d-8e4f-0b0000000058",
            "00000059-1a2b-4c3d-8e4f-0b0000000059",
            "0000005a-1a2b-4c3d-8e4f-0b000000005a",
            "0000005b-1a2b-4c3d-8e4f-0b000000005b",
            "0000005c-1a2b-4c3d-8e4f-0b000000005c",
            "0000005d-1a2b-4c3d-8e4f-0b000000005d",
            "0000005e-1a2b-4c3d-8e4f-0b000000005e",
            "0000005f-1a2b-4c3d-8e4f-0b000000005f",
            "00000060-1a2b-4c3d-8e4f-0b0000000060",
            "00000061-1a2b-4c3d-8e4f-0b0000000061",
            "00000062-1a2b-4c3d-8e4f-0b0000000062",
            "00000063-1a2b-4c3d-8e4f-0b0000000063",
            "00000064-1a2b-4c3d-8e4f-0b0000000064",
            "00000065-1a2b-4c3d-8e4f-0b0000000065"
        ],
        "readAt": "2026-09-08T12:00:00.000Z"
    }'''

    # Execute Request
    api_notifications_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="PUT",
        body=api_notifications_PUT_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_PUT_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_PUT_response, "message") == "Cannot update more than 100 notifications at once"

    # Request Body
    api_notifications_DELETE_request_body = r'''{
        "ids": [
            "00000001-1a2b-4c3d-8e4f-0b0000000001",
            "00000002-1a2b-4c3d-8e4f-0b0000000002",
            "00000003-1a2b-4c3d-8e4f-0b0000000003",
            "00000004-1a2b-4c3d-8e4f-0b0000000004",
            "00000005-1a2b-4c3d-8e4f-0b0000000005",
            "00000006-1a2b-4c3d-8e4f-0b0000000006",
            "00000007-1a2b-4c3d-8e4f-0b0000000007",
            "00000008-1a2b-4c3d-8e4f-0b0000000008",
            "00000009-1a2b-4c3d-8e4f-0b0000000009",
            "0000000a-1a2b-4c3d-8e4f-0b000000000a",
            "0000000b-1a2b-4c3d-8e4f-0b000000000b",
            "0000000c-1a2b-4c3d-8e4f-0b000000000c",
            "0000000d-1a2b-4c3d-8e4f-0b000000000d",
            "0000000e-1a2b-4c3d-8e4f-0b000000000e",
            "0000000f-1a2b-4c3d-8e4f-0b000000000f",
            "00000010-1a2b-4c3d-8e4f-0b0000000010",
            "00000011-1a2b-4c3d-8e4f-0b0000000011",
            "00000012-1a2b-4c3d-8e4f-0b0000000012",
            "00000013-1a2b-4c3d-8e4f-0b0000000013",
            "00000014-1a2b-4c3d-8e4f-0b0000000014",
            "00000015-1a2b-4c3d-8e4f-0b0000000015",
            "00000016-1a2b-4c3d-8e4f-0b0000000016",
            "00000017-1a2b-4c3d-8e4f-0b0000000017",
            "00000018-1a2b-4c3d-8e4f-0b0000000018",
            "00000019-1a2b-4c3d-8e4f-0b0000000019",
            "0000001a-1a2b-4c3d-8e4f-0b000000001a",
            "0000001b-1a2b-4c3d-8e4f-0b000000001b",
            "0000001c-1a2b-4c3d-8e4f-0b000000001c",
            "0000001d-1a2b-4c3d-8e4f-0b000000001d",
            "0000001e-1a2b-4c3d-8e4f-0b000000001e",
            "0000001f-1a2b-4c3d-8e4f-0b000000001f",
            "00000020-1a2b-4c3d-8e4f-0b0000000020",
            "00000021-1a2b-4c3d-8e4f-0b0000000021",
            "00000022-1a2b-4c3d-8e4f-0b0000000022",
            "00000023-1a2b-4c3d-8e4f-0b0000000023",
            "00000024-1a2b-4c3d-8e4f-0b0000000024",
            "00000025-1a2b-4c3d-8e4f-0b0000000025",
            "00000026-1a2b-4c3d-8e4f-0b0000000026",
            "00000027-1a2b-4c3d-8e4f-0b0000000027",
            "00000028-1a2b-4c3d-8e4f-0b0000000028",
            "00000029-1a2b-4c3d-8e4f-0b0000000029",
            "0000002a-1a2b-4c3d-8e4f-0b000000002a",
            "0000002b-1a2b-4c3d-8e4f-0b000000002b",
            "0000002c-1a2b-4c3d-8e4f-0b000000002c",
            "0000002d-1a2b-4c3d-8e4f-0b000000002d",
            "0000002e-1a2b-4c3d-8e4f-0b000000002e",
            "0000002f-1a2b-4c3d-8e4f-0b000000002f",
            "00000030-1a2b-4c3d-8e4f-0b0000000030",
            "00000031-1a2b-4c3d-8e4f-0b0000000031",
            "00000032-1a2b-4c3d-8e4f-0b0000000032",
            "00000033-1a2b-4c3d-8e4f-0b0000000033",
            "00000034-1a2b-4c3d-8e4f-0b0000000034",
            "00000035-1a2b-4c3d-8e4f-0b0000000035",
            "00000036-1a2b-4c3d-8e4f-0b0000000036",
            "00000037-1a2b-4c3d-8e4f-0b0000000037",
            "00000038-1a2b-4c3d-8e4f-0b0000000038",
            "00000039-1a2b-4c3d-8e4f-0b0000000039",
            "0000003a-1a2b-4c3d-8e4f-0b000000003a",
            "0000003b-1a2b-4c3d-8e4f-0b000000003b",
            "0000003c-1a2b-4c3d-8e4f-0b000000003c",
            "0000003d-1a2b-4c3d-8e4f-0b000000003d",
            "0000003e-1a2b-4c3d-8e4f-0b000000003e",
            "0000003f-1a2b-4c3d-8e4f-0b000000003f",
            "00000040-1a2b-4c3d-8e4f-0b0000000040",
            "00000041-1a2b-4c3d-8e4f-0b0000000041",
            "00000042-1a2b-4c3d-8e4f-0b0000000042",
            "00000043-1a2b-4c3d-8e4f-0b0000000043",
            "00000044-1a2b-4c3d-8e4f-0b0000000044",
            "00000045-1a2b-4c3d-8e4f-0b0000000045",
            "00000046-1a2b-4c3d-8e4f-0b0000000046",
            "00000047-1a2b-4c3d-8e4f-0b0000000047",
            "00000048-1a2b-4c3d-8e4f-0b0000000048",
            "00000049-1a2b-4c3d-8e4f-0b0000000049",
            "0000004a-1a2b-4c3d-8e4f-0b000000004a",
            "0000004b-1a2b-4c3d-8e4f-0b000000004b",
            "0000004c-1a2b-4c3d-8e4f-0b000000004c",
            "0000004d-1a2b-4c3d-8e4f-0b000000004d",
            "0000004e-1a2b-4c3d-8e4f-0b000000004e",
            "0000004f-1a2b-4c3d-8e4f-0b000000004f",
            "00000050-1a2b-4c3d-8e4f-0b0000000050",
            "00000051-1a2b-4c3d-8e4f-0b0000000051",
            "00000052-1a2b-4c3d-8e4f-0b0000000052",
            "00000053-1a2b-4c3d-8e4f-0b0000000053",
            "00000054-1a2b-4c3d-8e4f-0b0000000054",
            "00000055-1a2b-4c3d-8e4f-0b0000000055",
            "00000056-1a2b-4c3d-8e4f-0b0000000056",
            "00000057-1a2b-4c3d-8e4f-0b0000000057",
            "00000058-1a2b-4c3d-8e4f-0b0000000058",
            "00000059-1a2b-4c3d-8e4f-0b0000000059",
            "0000005a-1a2b-4c3d-8e4f-0b000000005a",
            "0000005b-1a2b-4c3d-8e4f-0b000000005b",
            "0000005c-1a2b-4c3d-8e4f-0b000000005c",
            "0000005d-1a2b-4c3d-8e4f-0b000000005d",
            "0000005e-1a2b-4c3d-8e4f-0b000000005e",
            "0000005f-1a2b-4c3d-8e4f-0b000000005f",
            "00000060-1a2b-4c3d-8e4f-0b0000000060",
            "00000061-1a2b-4c3d-8e4f-0b0000000061",
            "00000062-1a2b-4c3d-8e4f-0b0000000062",
            "00000063-1a2b-4c3d-8e4f-0b0000000063",
            "00000064-1a2b-4c3d-8e4f-0b0000000064",
            "00000065-1a2b-4c3d-8e4f-0b0000000065"
        ]
    }'''

    # Execute Request
    api_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=api_notifications_DELETE_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_DELETE_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_DELETE_response, "message") == "Cannot delete more than 100 notifications at once"

    # Request Body
    api_notifications_DELETE_1_request_body = r'''{
        "ids": [
            "22222222-3333-4444-8555-666666666666"
        ],
        "read": true
    }'''

    # Execute Request
    api_notifications_DELETE_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=api_notifications_DELETE_1_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_DELETE_1_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_DELETE_1_response, "message") == "Send either a list of ids or read, not both"

    # Request Body
    api_notifications_DELETE_2_request_body = r'''{}'''

    # Execute Request
    api_notifications_DELETE_2_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=api_notifications_DELETE_2_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_DELETE_2_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_DELETE_2_response, "message") == "Send either a list of ids or read"


if __name__ == "__main__":
    test_integration()
