# Generated by Skyramp v1.3.44 on 2026-09-08 21:28:50.247171503 +0000 UTC m=+2541.570210394
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notification_statistics_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notification_statistics_lifecycle.json

# Import of required libraries
import skyramp
import os
import re
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(me_GET_response, "id"), re.I)
    assert "@" in skyramp.get_response_value(me_GET_response, "email")
    assert skyramp.get_response_value(me_GET_response, "isAdmin") == True

    # Request Body
    notifications_POST_request_body = r'''{
        "description": "statistics lifecycle probe",
        "title": "Skyramp Stats Lifecycle",
        "userId": "1293a3b5-2b75-4f56-9dac-244b2996cf86"
    }'''

    # Execute Request
    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_request_body,
        headers=headers,
        data_override={"userId": skyramp.get_response_value(me_GET_response, "id")}
    )

    # Generated Assertions
    assert notifications_POST_response.status_code == 201
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(notifications_POST_response, "id"), re.I)
    assert re.match(r"^\d{4}-\d{2}-\d{2}T", skyramp.get_response_value(notifications_POST_response, "createdAt"))
    assert skyramp.get_response_value(notifications_POST_response, "title") == "Skyramp Stats Lifecycle"
    assert skyramp.get_response_value(notifications_POST_response, "description") == "statistics lifecycle probe"
    assert skyramp.get_response_value(notifications_POST_response, "level") == "info"
    assert skyramp.get_response_value(notifications_POST_response, "type") == "Custom"

    # Execute Request
    notifications_notifications_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="GET",
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_response, "id")}
    )

    # Generated Assertions
    assert notifications_notifications_GET_response.status_code == 200
    assert skyramp.get_response_value(notifications_notifications_GET_response, "id") == skyramp.get_response_value(notifications_POST_response, "id")
    assert skyramp.get_response_value(notifications_notifications_GET_response, "title") == "Skyramp Stats Lifecycle"
    assert skyramp.get_response_value(notifications_notifications_GET_response, "description") == "statistics lifecycle probe"
    assert skyramp.get_response_value(notifications_notifications_GET_response, "level") == "info"
    assert skyramp.get_response_value(notifications_notifications_GET_response, "type") == "Custom"

    # Execute Request
    statistics_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert statistics_GET_response.status_code == 200
    assert skyramp.get_response_value(statistics_GET_response, "total") == 1
    assert skyramp.get_response_value(statistics_GET_response, "unread") == 1

    # Request Body
    notifications_notifications_PUT_request_body = r'''{
        "readAt": "2026-09-08T21:00:00.000Z"
    }'''

    # Execute Request
    notifications_notifications_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="PUT",
        body=notifications_notifications_PUT_request_body,
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_response, "id")}
    )

    # Generated Assertions
    assert notifications_notifications_PUT_response.status_code == 200
    assert skyramp.get_response_value(notifications_notifications_PUT_response, "id") == skyramp.get_response_value(notifications_POST_response, "id")
    assert skyramp.get_response_value(notifications_notifications_PUT_response, "readAt") == "2026-09-08T21:00:00.000Z"
    assert skyramp.get_response_value(notifications_notifications_PUT_response, "title") == "Skyramp Stats Lifecycle"

    # Execute Request
    statistics_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert statistics_GET_1_response.status_code == 200
    assert skyramp.get_response_value(statistics_GET_1_response, "total") == 1
    assert skyramp.get_response_value(statistics_GET_1_response, "unread") == 0

    # Request Body
    api_notifications_DELETE_request_body = r'''{
        "read": true
    }'''

    # Execute Request
    api_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=api_notifications_DELETE_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_DELETE_response.status_code == 204

    # Execute Request
    statistics_GET_2_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/statistics",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert statistics_GET_2_response.status_code == 200
    assert skyramp.get_response_value(statistics_GET_2_response, "total") == 0
    assert skyramp.get_response_value(statistics_GET_2_response, "unread") == 0

    # Execute Request
    notifications_notifications_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="GET",
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_response, "id")}
    )

    # Generated Assertions
    assert notifications_notifications_GET_1_response.status_code == 404
    assert skyramp.get_response_value(notifications_notifications_GET_1_response, "message") == "Notification not found"

    # Execute Request
    notifications_6f3a1c9e_2b47_4d58_9e10_8c5d7a2b4f61_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/6f3a1c9e-2b47-4d58-9e10-8c5d7a2b4f61",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert notifications_6f3a1c9e_2b47_4d58_9e10_8c5d7a2b4f61_GET_response.status_code == 404
    assert skyramp.get_response_value(notifications_6f3a1c9e_2b47_4d58_9e10_8c5d7a2b4f61_GET_response, "message") == "Notification not found"


if __name__ == "__main__":
    test_integration()
