# Generated by Skyramp v1.3.44 on 2026-09-12 18:56:30.561005303 +0000 UTC m=+1607.782442286
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notification_bulk_id_cap_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notification_bulk_id_cap.json

# Import of required libraries
import skyramp
import os
import time
import re
import json
import uuid


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

UUID_RE = r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
ISO_RE = r"^\d{4}-\d{2}-\d{2}T"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")
    headers["Content-Type"] = "application/json"

    run = uuid.uuid4().hex[:8]

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    user_id = skyramp.get_response_value(me_GET_response, "id")
    assert re.match(UUID_RE, str(user_id), re.IGNORECASE)

    read_at = "2026-09-12T18:00:00.000Z"
    title = "testbot-bulkcap-" + run
    ids_over_cap = [str(uuid.uuid4()) for _ in range(101)]

    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=json.dumps({"userId": user_id, "title": title}),
        headers=headers
    )
    assert notifications_POST_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_response, "title") == title
    notification_id = skyramp.get_response_value(notifications_POST_response, "id")
    assert re.match(UUID_RE, str(notification_id), re.IGNORECASE)

    # A bulk update of one owned id is accepted
    api_notifications_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="PUT",
        body=json.dumps({"ids": [notification_id], "readAt": read_at}),
        headers=headers
    )
    assert api_notifications_PUT_response.status_code == 204

    read_back_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/" + str(notification_id),
        method="GET",
        headers=headers
    )
    assert read_back_GET_response.status_code == 200
    assert skyramp.get_response_value(read_back_GET_response, "readAt") == read_at

    # 101 ids is over the cap on update
    api_notifications_PUT_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="PUT",
        body=json.dumps({"ids": ids_over_cap, "readAt": read_at}),
        headers=headers
    )
    assert api_notifications_PUT_1_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_PUT_1_response, "message") == "Cannot update more than 100 notifications at once"

    # 101 ids is over the cap on delete
    api_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=json.dumps({"ids": ids_over_cap}),
        headers=headers
    )
    assert api_notifications_DELETE_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_DELETE_response, "message") == "Cannot delete more than 100 notifications at once"

    # ids and read together is refused
    api_notifications_DELETE_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=json.dumps({"ids": [notification_id], "read": True}),
        headers=headers
    )
    assert api_notifications_DELETE_1_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_DELETE_1_response, "message") == "Send either a list of ids or read, not both"

    # neither ids nor read is refused
    api_notifications_DELETE_2_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=json.dumps({}),
        headers=headers
    )
    assert api_notifications_DELETE_2_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_DELETE_2_response, "message") == "Send either a list of ids or read"

    # read false with no ids is refused
    api_notifications_DELETE_3_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=json.dumps({"read": False}),
        headers=headers
    )
    assert api_notifications_DELETE_3_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_DELETE_3_response, "message") == "Send either a list of ids or read"

    # None of the refused requests removed the notice
    still_there_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/" + str(notification_id),
        method="GET",
        headers=headers
    )
    assert still_there_GET_response.status_code == 200
    assert skyramp.get_response_value(still_there_GET_response, "id") == notification_id

    # Delete the record this test created
    api_notifications_DELETE_4_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=json.dumps({"ids": [notification_id]}),
        headers=headers
    )
    assert api_notifications_DELETE_4_response.status_code == 204

    gone_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/" + str(notification_id),
        method="GET",
        headers=headers
    )
    assert gone_GET_response.status_code == 404
    assert skyramp.get_response_value(gone_GET_response, "message") == "Notification not found"
