# Generated by Skyramp v1.3.44 on 2026-09-08 21:14:19.884235372 +0000 UTC m=+1546.468525102
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notification_clear_read_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notification_clear_read.json

# Import of required libraries
import skyramp
import os
import json
import re
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    assert skyramp.get_response_value(me_GET_response, "isAdmin") is True

    # Request Body
    notifications_POST_request_body = r'''{
        "level": "info",
        "title": "Skyramp clear read probe read",
        "userId": "6ecb082e-4c2a-4668-ab6d-0bd4091f9c13"
    }'''

    # Execute Request
    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_request_body,
        headers=headers,
        data_override={"userId": skyramp.get_response_value(me_GET_response, "id")}
    )

    # Generated Assertions
    assert notifications_POST_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_response, "title") == "Skyramp clear read probe read"

    # Request Body
    notifications_POST_1_request_body = r'''{
        "level": "info",
        "title": "Skyramp clear read probe unread",
        "userId": "6ecb082e-4c2a-4668-ab6d-0bd4091f9c13"
    }'''

    # Execute Request
    notifications_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_1_request_body,
        headers=headers,
        data_override={"userId": skyramp.get_response_value(me_GET_response, "id")}
    )

    # Generated Assertions
    assert notifications_POST_1_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_1_response, "title") == "Skyramp clear read probe unread"
    assert skyramp.get_response_value(notifications_POST_1_response, "id") != skyramp.get_response_value(notifications_POST_response, "id")

    # Request Body
    notifications_notifications_PUT_request_body = r'''{
        "readAt": "2026-09-08T21:00:00.000Z"
    }'''

    # Execute Request
    notifications_notifications_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="PUT",
        body=notifications_notifications_PUT_request_body,
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_response, "id")},
        data_override={"readAt": skyramp.get_response_value(notifications_POST_response, "createdAt")}
    )

    # Generated Assertions
    assert notifications_notifications_PUT_response.status_code == 200
    assert skyramp.get_response_value(notifications_notifications_PUT_response, "id") == skyramp.get_response_value(notifications_POST_response, "id")
    assert re.match(r"^\d{4}-\d{2}-\d{2}T", skyramp.get_response_value(notifications_notifications_PUT_response, "readAt"))

    # Request Body
    api_notifications_DELETE_request_body = json.dumps({
        "ids": [skyramp.get_response_value(notifications_POST_response, "id")],
        "read": True
    })

    # Execute Request
    api_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=api_notifications_DELETE_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_DELETE_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_DELETE_response, "message") == "Send either a list of ids or read, not both"

    # Request Body
    api_notifications_DELETE_1_request_body = r'''{
        "read": false
    }'''

    # Execute Request
    api_notifications_DELETE_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=api_notifications_DELETE_1_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_DELETE_1_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_DELETE_1_response, "message") == "Send either a list of ids or read"

    # Request Body
    api_notifications_DELETE_2_request_body = r'''{
        "read": true
    }'''

    # Execute Request
    api_notifications_DELETE_2_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=api_notifications_DELETE_2_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_DELETE_2_response.status_code == 204

    # Execute Request
    notifications_notifications_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="GET",
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_response, "id")}
    )

    # Generated Assertions
    assert notifications_notifications_GET_response.status_code == 404
    assert skyramp.get_response_value(notifications_notifications_GET_response, "message") == "Notification not found"

    # Execute Request
    notifications_notifications_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="GET",
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_1_response, "id")}
    )

    # Generated Assertions
    assert notifications_notifications_GET_1_response.status_code == 200
    assert skyramp.get_response_value(notifications_notifications_GET_1_response, "id") == skyramp.get_response_value(notifications_POST_1_response, "id")
    assert skyramp.get_response_value(notifications_notifications_GET_1_response, "title") == "Skyramp clear read probe unread"
    assert skyramp.get_response_value(notifications_notifications_GET_1_response, "readAt") is None

    # Execute Request
    notifications_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="DELETE",
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_1_response, "id")}
    )

    # Generated Assertions
    assert notifications_notifications_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
