# Generated by Skyramp v1.3.44 on 2026-09-08 21:35:11.071698975 +0000 UTC m=+1952.444807298
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notifications_bulk_delete_cross_user_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notifications_bulk_delete_cross_user.json

# Import of required libraries
import skyramp
import json
import os
import re
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    unique_email = skyramp.unique_suffix("skyramp-boundary@immich.test")

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(me_GET_response, "id"), re.I)
    assert "@" in skyramp.get_response_value(me_GET_response, "email")
    caller_id = skyramp.get_response_value(me_GET_response, "id")

    # Request Body
    users_POST_request_body = r'''{
        "email": "skyramp-boundary@immich.test",
        "name": "Skyramp Boundary User",
        "password": "Skyramp#Pass123"
    }'''

    # Execute Request
    users_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/users",
        method="POST",
        body=users_POST_request_body,
        headers=headers,
        data_override={"email": unique_email}
    )

    # Generated Assertions
    assert users_POST_response.status_code == 201
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(users_POST_response, "id"), re.I)
    assert skyramp.get_response_value(users_POST_response, "email") == unique_email
    assert skyramp.get_response_value(users_POST_response, "name") == "Skyramp Boundary User"
    assert skyramp.get_response_value(users_POST_response, "isAdmin") is False
    foreign_user_id = skyramp.get_response_value(users_POST_response, "id")

    # Request Body
    notifications_POST_request_body = r'''{
        "title": "Foreign Notice",
        "userId": "aaaaaaa2-1a2b-4c3d-8e4f-0a0000000002"
    }'''

    # Execute Request
    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_request_body,
        headers=headers,
        data_override={"userId": foreign_user_id}
    )

    # Generated Assertions
    assert notifications_POST_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_response, "title") == "Foreign Notice"
    assert skyramp.get_response_value(notifications_POST_response, "level") == "info"
    assert skyramp.get_response_value(notifications_POST_response, "type") == "Custom"
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(notifications_POST_response, "id"), re.I)
    assert re.match(r"^\d{4}-\d{2}-\d{2}T", skyramp.get_response_value(notifications_POST_response, "createdAt"))
    foreign_notification_id = skyramp.get_response_value(notifications_POST_response, "id")

    # Execute Request
    notifications_notifications_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications/{notifications}",
        method="GET",
        headers=headers,
        path_params={"notifications": skyramp.get_response_value(notifications_POST_response, "id")}
    )

    # Generated Assertions
    assert notifications_notifications_GET_response.status_code == 400
    assert skyramp.get_response_value(notifications_notifications_GET_response, "message") == "Not found or no notification.read access"

    # Request Body
    notifications_POST_1_request_body = r'''{
        "title": "Own Notice",
        "userId": "aaaaaaa1-1a2b-4c3d-8e4f-0a0000000001"
    }'''

    # Execute Request
    notifications_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_1_request_body,
        headers=headers,
        data_override={"userId": caller_id}
    )

    # Generated Assertions
    assert notifications_POST_1_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_1_response, "title") == "Own Notice"
    assert skyramp.get_response_value(notifications_POST_1_response, "level") == "info"
    assert skyramp.get_response_value(notifications_POST_1_response, "type") == "Custom"
    own_notification_id = skyramp.get_response_value(notifications_POST_1_response, "id")

    # Request Body
    api_notifications_DELETE_request_body = json.dumps({"ids": [own_notification_id]})

    # Execute Request
    api_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=api_notifications_DELETE_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_DELETE_response.status_code == 204

    # Request Body
    api_notifications_DELETE_1_request_body = json.dumps({"ids": [foreign_notification_id]})

    # Execute Request
    api_notifications_DELETE_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=api_notifications_DELETE_1_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_DELETE_1_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_DELETE_1_response, "message") == "Not found or no notification.delete access"

    # Request Body
    users_users_DELETE_request_body = r'''{
        "force": true
    }'''

    # Execute Request
    users_users_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/users/{users}",
        method="DELETE",
        body=users_users_DELETE_request_body,
        headers=headers,
        path_params={"users": skyramp.get_response_value(users_POST_response, "id")}
    )

    # Generated Assertions
    assert users_users_DELETE_response.status_code == 200
    assert skyramp.get_response_value(users_users_DELETE_response, "id") == foreign_user_id


if __name__ == "__main__":
    test_integration()
