# Generated by Skyramp v1.3.44 on 2026-09-08 21:14:24.878830674 +0000 UTC m=+1551.463120409
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output notification_search_filter_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_notification_search_filter.json

# Import of required libraries
import skyramp
import os
import json
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    search = ""

    # Execute Request
    me_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    assert skyramp.get_response_value(me_GET_response, "isAdmin") is True

    # Request Body
    notifications_POST_request_body = r'''{
        "description": "generic body for the title match",
        "level": "info",
        "title": "Skyramp anemone audit",
        "userId": "6ecb082e-4c2a-4668-ab6d-0bd4091f9c13"
    }'''

    # Execute Request
    notifications_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_request_body,
        headers=headers,
        data_override={"userId": skyramp.get_response_value(me_GET_response, "id")}
    )

    # Generated Assertions
    assert notifications_POST_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_response, "title") == "Skyramp anemone audit"
    assert skyramp.get_response_value(notifications_POST_response, "description") == "generic body for the title match"

    # Request Body
    notifications_POST_1_request_body = r'''{
        "description": "basalt reminder in the description only",
        "level": "info",
        "title": "Skyramp generic heading",
        "userId": "6ecb082e-4c2a-4668-ab6d-0bd4091f9c13"
    }'''

    # Execute Request
    notifications_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/notifications",
        method="POST",
        body=notifications_POST_1_request_body,
        headers=headers,
        data_override={"userId": skyramp.get_response_value(me_GET_response, "id")}
    )

    # Generated Assertions
    assert notifications_POST_1_response.status_code == 201
    assert skyramp.get_response_value(notifications_POST_1_response, "title") == "Skyramp generic heading"
    assert skyramp.get_response_value(notifications_POST_1_response, "description") == "basalt reminder in the description only"

    # Execute Request
    api_notifications_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": ["anemone"]}
    )

    # Generated Assertions
    assert api_notifications_GET_response.status_code == 200
    assert skyramp.get_response_value(api_notifications_GET_response, "0.id") == skyramp.get_response_value(notifications_POST_response, "id")
    assert skyramp.get_response_value(api_notifications_GET_response, "0.title") == "Skyramp anemone audit"
    assert skyramp.get_response_value(api_notifications_GET_response, "1") is None

    # Execute Request
    api_notifications_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": ["basalt"]}
    )

    # Generated Assertions
    assert api_notifications_GET_1_response.status_code == 200
    assert skyramp.get_response_value(api_notifications_GET_1_response, "0.id") == skyramp.get_response_value(notifications_POST_1_response, "id")
    assert skyramp.get_response_value(api_notifications_GET_1_response, "0.description") == "basalt reminder in the description only"
    assert skyramp.get_response_value(api_notifications_GET_1_response, "1") is None

    # Execute Request
    api_notifications_GET_2_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": ["zzznomatchzzz"]}
    )

    # Generated Assertions
    assert api_notifications_GET_2_response.status_code == 200
    assert skyramp.get_response_value(api_notifications_GET_2_response, "0") is None

    # Execute Request
    api_notifications_GET_3_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="GET",
        headers=headers,
        query_params={"search": [""]}
    )

    # Generated Assertions
    assert api_notifications_GET_3_response.status_code == 400
    assert skyramp.get_response_value(api_notifications_GET_3_response, "message") == "Validation failed"
    assert skyramp.get_response_value(api_notifications_GET_3_response, "errors.0.path.0") == "search"
    assert skyramp.get_response_value(api_notifications_GET_3_response, "errors.1") is None

    # Request Body
    api_notifications_DELETE_request_body = json.dumps({
        "ids": [
            skyramp.get_response_value(notifications_POST_response, "id"),
            skyramp.get_response_value(notifications_POST_1_response, "id")
        ]
    })

    # Execute Request
    api_notifications_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/notifications",
        method="DELETE",
        body=api_notifications_DELETE_request_body,
        headers=headers
    )

    # Generated Assertions
    assert api_notifications_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
