# Generated by Skyramp v1.3.44 on 2026-09-08 21:14:44.376855058 +0000 UTC m=+1570.961144801
# Command: skyramp generate ui rest \
# 		--framework pytest \
# 		--language python \
# 		--output ui_notification_centre_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--playwright-trace /home/runner/work/immich-testb/immich-testb/.skyramp/notification_centre_trace.zip

# Import of required libraries
import skyramp
import os
import pytest
import re
from skyramp import expect
from playwright.sync_api import Page


# URL for test requests
base_url = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

@pytest.fixture(scope="session")
def browser_context_args(browser_context_args, playwright):
    return {
        "ignore_https_errors": True,
        "service_workers": "block",
        "viewport": { "width": 1280, "height": 900 },
    }


def test_ui(page: Page):
    # set default timeout for all locator/page actions in this test
    page.set_default_timeout(15000)
    # Wrap playwright page with Skyramp page
    page = skyramp.new_skyramp_playwright_page(page)

    page.goto(f'{base_url}/auth/login')

    playwright_request_0 = {
        "email": "admin@immich.test",
        "password": "password"
    }

    page.locator("#email").fill(skyramp.get_value(playwright_request_0, "email"))
    page.locator("#password").fill(skyramp.get_value(playwright_request_0, "password"))
    # Wait to finish any potential hydration
    page.wait_for_timeout(1500)
    with page.expect_response("**/api/auth/login**") as response_0:
        page.get_by_role("button", name="Login").click()

    # Wait for network activities to finish
    page.wait_for_timeout(3000)

    page.wait_for_url(lambda url: "/auth/login" not in url)
    expect(page.get_by_role("button", name="Admin (admin@immich.test)")).to_be_visible()
    page.goto(f'{base_url}/admin/users')
    page.get_by_role("link", name="Admin").click()
    expect(page.get_by_test_id("send-notification-submit")).to_be_disabled()

    playwright_request_1 = {
        "description": "Please review your shared albums before Friday",
        "title": "Quarterly library audit"
    }

    page.get_by_test_id("send-notification-title").fill(skyramp.get_value(playwright_request_1, "title"))
    page.get_by_test_id("send-notification-description").fill(skyramp.get_value(playwright_request_1, "description"))
    expect(page.get_by_test_id("send-notification-submit")).to_be_enabled()
    # Wait to finish any potential hydration
    page.wait_for_timeout(1500)
    with page.expect_response("**/api/**/notifications**") as response_1:
        page.get_by_test_id("send-notification-submit").click()

    # Wait for network activities to finish
    page.wait_for_timeout(3000)

    expect(page.get_by_test_id("send-notification-submit")).to_be_disabled()
    page.goto(f'{base_url}/photos')
    expect(page.get_by_test_id("notification-unread-badge")).to_have_text("1")
    page.get_by_role("button", name="Notifications").click()
    expect(page.get_by_test_id("notification-clear-read")).to_be_disabled()
    expect(page.get_by_test_id("notification-item")).to_contain_text("Quarterly library audit")
    page.get_by_test_id("notification-search").fill("shared albums")
    expect(page.get_by_test_id("notification-item")).to_contain_text("Quarterly library audit")
    page.get_by_test_id("notification-search").fill("monthly invoice reminder")
    expect(page.get_by_test_id("notification-item")).to_be_hidden()
    expect(page.get_by_text("No notifications", exact=True)).to_be_visible()
    page.get_by_test_id("notification-search").fill("")
    # Wait to finish any potential hydration
    page.wait_for_timeout(1500)
    with page.expect_response("**/api/notifications/**") as response_2:
        page.get_by_test_id("notification-item").click()

    # Wait for network activities to finish
    page.wait_for_timeout(3000)

    expect(page.get_by_test_id("notification-clear-read")).to_be_enabled()
    expect(page.get_by_role("button", name="Mark all as read")).to_be_disabled()
    expect(page.get_by_test_id("notification-unread-badge")).to_be_hidden()
    page.get_by_test_id("notification-show-read").click()
    expect(page.get_by_test_id("notification-item")).to_contain_text("Quarterly library audit")
    page.get_by_test_id("notification-remove").click()
    expect(page.get_by_test_id("notification-item")).to_be_hidden()
    expect(page.get_by_text("No notifications", exact=True)).to_be_visible()
    expect(page.get_by_test_id("notification-show-read")).to_be_checked()
    expect(page.get_by_test_id("notification-clear-read")).to_be_disabled()
